DEF=$(basename $@)
KOMPILED_DIR=$(DEF)-kompiled
KDEP_FLAGS= --output-definition OutputDirectoryTest/$(KOMPILED_DIR) --no-prelude -I IncludeDirTest

include ../../../../include/kframework/ktest-kdep.mak
