name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/k'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update K Version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Update K version'
        run: |
          K_VERSION=$(cat deps/k_release)
          sed --in-place "s/^K_VERSION: Final = '.*'$/K_VERSION: Final = '${K_VERSION}'/" src/pyk/__init__.py
          git add --update && git commit -m "Set K Version: ${K_VERSION}" || true
      - name: 'Push updates'
        run: git push
