
# this is the name of the main maude module 
LANGUAGE_NAME = CALLCC-TEST

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = K-VISITOR SUBSTITUTION LAMBDA CALLCC

#this is the basename of the main file
MAIN_FILE = callcc-test

# this is a space-separated list of basename maude files to run
TESTS = test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
