DEF=../boundary-cells-test
EXT=a
TESTDIR=..
RESULTDIR=.

KOMPILE_FLAGS=--syntax-module BOUNDARY-CELLS-TEST
KOMPILE_BACKEND?=java

KPROVE_FLAGS=--boundary-cells c1

include ../../../../include/ktest.mak
