# this is the name of the main maude module
LANGUAGE_NAME = TEST

# this is the name of the interesting modules (used by make latex/pdf)
LANGUAGE_MODULES = TEST

# this is the basename of the main file
MAIN_FILE = test

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
