load befunge-compiled
mod BEFUNGE-TEST is
	including BEFUNGE .
	
	--- equivalent to the b93 program from the fungus test suite found at http://www.phlamethrower.co.uk/befunge/fungus.php
	op pB93 : -> KProperLabel [metadata "arity 0"] .
	eq pB93 = injectM( __(.,(.
	coord(inject(0)(.List{K}),, inject(0)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(1)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(0)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(0)(.List{K})) |-> inject("X")(.List{K})
	coord(inject(0)(.List{K}),, inject(1)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(1)(.List{K}),, inject(1)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(2)(.List{K}),, inject(1)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(3)(.List{K}),, inject(1)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(4)(.List{K}),, inject(1)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(5)(.List{K}),, inject(1)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(6)(.List{K}),, inject(1)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(7)(.List{K}),, inject(1)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(8)(.List{K}),, inject(1)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(9)(.List{K}),, inject(1)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(10)(.List{K}),, inject(1)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(11)(.List{K}),, inject(1)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(12)(.List{K}),, inject(1)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(1)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(14)(.List{K}),, inject(1)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(15)(.List{K}),, inject(1)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(1)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(17)(.List{K}),, inject(1)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(18)(.List{K}),, inject(1)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(19)(.List{K}),, inject(1)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(20)(.List{K}),, inject(1)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(21)(.List{K}),, inject(1)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(22)(.List{K}),, inject(1)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(23)(.List{K}),, inject(1)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(24)(.List{K}),, inject(1)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(25)(.List{K}),, inject(1)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(26)(.List{K}),, inject(1)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(27)(.List{K}),, inject(1)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(28)(.List{K}),, inject(1)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(29)(.List{K}),, inject(1)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(30)(.List{K}),, inject(1)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(31)(.List{K}),, inject(1)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(32)(.List{K}),, inject(1)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(1)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(34)(.List{K}),, inject(1)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(35)(.List{K}),, inject(1)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(1)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(37)(.List{K}),, inject(1)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(38)(.List{K}),, inject(1)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(39)(.List{K}),, inject(1)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(2)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(1)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(2)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(3)(.List{K}),, inject(2)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(4)(.List{K}),, inject(2)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(5)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(2)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(7)(.List{K}),, inject(2)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(8)(.List{K}),, inject(2)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(9)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(2)(.List{K})) |-> inject("^")(.List{K})
	coord(inject(20)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(49)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(51)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(53)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(54)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(55)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(58)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(59)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(60)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(61)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(62)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(63)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(64)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(65)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(66)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(67)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(68)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(69)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(70)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(71)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(72)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(73)(.List{K}),, inject(2)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(74)(.List{K}),, inject(2)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(75)(.List{K}),, inject(2)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(76)(.List{K}),, inject(2)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(77)(.List{K}),, inject(2)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(78)(.List{K}),, inject(2)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(79)(.List{K}),, inject(2)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(0)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(3)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(16)(.List{K}),, inject(3)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(17)(.List{K}),, inject(3)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(18)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(3)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(20)(.List{K}),, inject(3)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(21)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(3)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(23)(.List{K}),, inject(3)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(24)(.List{K}),, inject(3)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(25)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(3)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(27)(.List{K}),, inject(3)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(28)(.List{K}),, inject(3)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(29)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(3)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(3)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(36)(.List{K}),, inject(3)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(37)(.List{K}),, inject(3)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(38)(.List{K}),, inject(3)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(39)(.List{K}),, inject(3)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(4)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(1)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(4)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(36)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(4)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(38)(.List{K}),, inject(4)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(39)(.List{K}),, inject(4)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(40)(.List{K}),, inject(4)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(41)(.List{K}),, inject(4)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(42)(.List{K}),, inject(4)(.List{K})) |-> inject("W")(.List{K})
	coord(inject(43)(.List{K}),, inject(4)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(44)(.List{K}),, inject(4)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(45)(.List{K}),, inject(4)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(46)(.List{K}),, inject(4)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(47)(.List{K}),, inject(4)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(48)(.List{K}),, inject(4)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(49)(.List{K}),, inject(4)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(50)(.List{K}),, inject(4)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(51)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(4)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(53)(.List{K}),, inject(4)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(54)(.List{K}),, inject(4)(.List{K})) |-> inject("g")(.List{K})
	coord(inject(55)(.List{K}),, inject(4)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(56)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(4)(.List{K})) |-> inject("j")(.List{K})
	coord(inject(58)(.List{K}),, inject(4)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(59)(.List{K}),, inject(4)(.List{K})) |-> inject("m")(.List{K})
	coord(inject(60)(.List{K}),, inject(4)(.List{K})) |-> inject("p")(.List{K})
	coord(inject(61)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(62)(.List{K}),, inject(4)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(63)(.List{K}),, inject(4)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(64)(.List{K}),, inject(4)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(65)(.List{K}),, inject(4)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(66)(.List{K}),, inject(4)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(67)(.List{K}),, inject(4)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(68)(.List{K}),, inject(4)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(69)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(70)(.List{K}),, inject(4)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(71)(.List{K}),, inject(4)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(72)(.List{K}),, inject(4)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(73)(.List{K}),, inject(4)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(74)(.List{K}),, inject(4)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(75)(.List{K}),, inject(4)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(76)(.List{K}),, inject(4)(.List{K})) |-> inject("7")(.List{K})
	coord(inject(77)(.List{K}),, inject(4)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(78)(.List{K}),, inject(4)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(79)(.List{K}),, inject(4)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(5)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(20)(.List{K}),, inject(5)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(21)(.List{K}),, inject(5)(.List{K})) |-> inject("$")(.List{K})
	coord(inject(22)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(5)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(24)(.List{K}),, inject(5)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(25)(.List{K}),, inject(5)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(26)(.List{K}),, inject(5)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(27)(.List{K}),, inject(5)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(28)(.List{K}),, inject(5)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(29)(.List{K}),, inject(5)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(30)(.List{K}),, inject(5)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(31)(.List{K}),, inject(5)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(32)(.List{K}),, inject(5)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(33)(.List{K}),, inject(5)(.List{K})) |-> inject("4")(.List{K})
	coord(inject(34)(.List{K}),, inject(5)(.List{K})) |-> inject("$")(.List{K})
	coord(inject(35)(.List{K}),, inject(5)(.List{K})) |-> inject("4")(.List{K})
	coord(inject(36)(.List{K}),, inject(5)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(37)(.List{K}),, inject(5)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(38)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(49)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(51)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(53)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(54)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(55)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(58)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(59)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(60)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(61)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(62)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(63)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(64)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(65)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(66)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(67)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(68)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(69)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(70)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(71)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(72)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(73)(.List{K}),, inject(5)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(74)(.List{K}),, inject(5)(.List{K})) |-> inject("^")(.List{K})
	coord(inject(75)(.List{K}),, inject(5)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(76)(.List{K}),, inject(5)(.List{K})) |-> inject("8")(.List{K})
	coord(inject(77)(.List{K}),, inject(5)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(78)(.List{K}),, inject(5)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(79)(.List{K}),, inject(5)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(6)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(20)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(6)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(30)(.List{K}),, inject(6)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(31)(.List{K}),, inject(6)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(32)(.List{K}),, inject(6)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(33)(.List{K}),, inject(6)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(34)(.List{K}),, inject(6)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(35)(.List{K}),, inject(6)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(36)(.List{K}),, inject(6)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(37)(.List{K}),, inject(6)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(38)(.List{K}),, inject(6)(.List{K})) |-> inject("b")(.List{K})
	coord(inject(39)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(6)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(41)(.List{K}),, inject(6)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(42)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(6)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(44)(.List{K}),, inject(6)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(45)(.List{K}),, inject(6)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(6)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(7)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(30)(.List{K}),, inject(7)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(31)(.List{K}),, inject(7)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(32)(.List{K}),, inject(7)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(33)(.List{K}),, inject(7)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(34)(.List{K}),, inject(7)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(35)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(7)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(37)(.List{K}),, inject(7)(.List{K})) |-> inject("'")(.List{K})
	coord(inject(38)(.List{K}),, inject(7)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(39)(.List{K}),, inject(7)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(40)(.List{K}),, inject(7)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(41)(.List{K}),, inject(7)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(42)(.List{K}),, inject(7)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(43)(.List{K}),, inject(7)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(7)(.List{K})) |-> inject("$")(.List{K})
	coord(inject(45)(.List{K}),, inject(7)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(46)(.List{K}),, inject(7)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(8)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(18)(.List{K}),, inject(8)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(19)(.List{K}),, inject(8)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(20)(.List{K}),, inject(8)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(21)(.List{K}),, inject(8)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(22)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(8)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(24)(.List{K}),, inject(8)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(25)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(8)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(27)(.List{K}),, inject(8)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(28)(.List{K}),, inject(8)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(29)(.List{K}),, inject(8)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(8)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(31)(.List{K}),, inject(8)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(32)(.List{K}),, inject(8)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(33)(.List{K}),, inject(8)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(34)(.List{K}),, inject(8)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(35)(.List{K}),, inject(8)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(36)(.List{K}),, inject(8)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(37)(.List{K}),, inject(8)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(38)(.List{K}),, inject(8)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(39)(.List{K}),, inject(8)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(40)(.List{K}),, inject(8)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(41)(.List{K}),, inject(8)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(42)(.List{K}),, inject(8)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(43)(.List{K}),, inject(8)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(44)(.List{K}),, inject(8)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(45)(.List{K}),, inject(8)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(46)(.List{K}),, inject(8)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(9)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(18)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(9)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(37)(.List{K}),, inject(9)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(38)(.List{K}),, inject(9)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(39)(.List{K}),, inject(9)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(40)(.List{K}),, inject(9)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(41)(.List{K}),, inject(9)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(42)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(9)(.List{K})) |-> inject("y")(.List{K})
	coord(inject(44)(.List{K}),, inject(9)(.List{K})) |-> inject("l")(.List{K})
	coord(inject(45)(.List{K}),, inject(9)(.List{K})) |-> inject("b")(.List{K})
	coord(inject(46)(.List{K}),, inject(9)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(47)(.List{K}),, inject(9)(.List{K})) |-> inject("b")(.List{K})
	coord(inject(48)(.List{K}),, inject(9)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(49)(.List{K}),, inject(9)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(50)(.List{K}),, inject(9)(.List{K})) |-> inject("p")(.List{K})
	coord(inject(51)(.List{K}),, inject(9)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(9)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(53)(.List{K}),, inject(9)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(54)(.List{K}),, inject(9)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(55)(.List{K}),, inject(9)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(56)(.List{K}),, inject(9)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(10)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(30)(.List{K}),, inject(10)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(31)(.List{K}),, inject(10)(.List{K})) |-> inject(":")(.List{K})
	coord(inject(32)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(10)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(34)(.List{K}),, inject(10)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(35)(.List{K}),, inject(10)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(36)(.List{K}),, inject(10)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(37)(.List{K}),, inject(10)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(38)(.List{K}),, inject(10)(.List{K})) |-> inject("'")(.List{K})
	coord(inject(39)(.List{K}),, inject(10)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(40)(.List{K}),, inject(10)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(10)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(42)(.List{K}),, inject(10)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(43)(.List{K}),, inject(10)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(44)(.List{K}),, inject(10)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(45)(.List{K}),, inject(10)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(46)(.List{K}),, inject(10)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(47)(.List{K}),, inject(10)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(48)(.List{K}),, inject(10)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(49)(.List{K}),, inject(10)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(50)(.List{K}),, inject(10)(.List{K})) |-> inject(":")(.List{K})
	coord(inject(51)(.List{K}),, inject(10)(.List{K})) |-> inject("4")(.List{K})
	coord(inject(52)(.List{K}),, inject(10)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(53)(.List{K}),, inject(10)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(54)(.List{K}),, inject(10)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(55)(.List{K}),, inject(10)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(56)(.List{K}),, inject(10)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(11)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(30)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(11)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(48)(.List{K}),, inject(11)(.List{K})) |-> inject("$")(.List{K})
	coord(inject(49)(.List{K}),, inject(11)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(50)(.List{K}),, inject(11)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(51)(.List{K}),, inject(11)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(52)(.List{K}),, inject(11)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(53)(.List{K}),, inject(11)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(54)(.List{K}),, inject(11)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(55)(.List{K}),, inject(11)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(11)(.List{K})) |-> inject(":")(.List{K})
	coord(inject(57)(.List{K}),, inject(11)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(58)(.List{K}),, inject(11)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(12)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(35)(.List{K}),, inject(12)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(36)(.List{K}),, inject(12)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(37)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(12)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(39)(.List{K}),, inject(12)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(40)(.List{K}),, inject(12)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(12)(.List{K})) |-> inject("b")(.List{K})
	coord(inject(42)(.List{K}),, inject(12)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(43)(.List{K}),, inject(12)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(44)(.List{K}),, inject(12)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(45)(.List{K}),, inject(12)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(46)(.List{K}),, inject(12)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(47)(.List{K}),, inject(12)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(48)(.List{K}),, inject(12)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(49)(.List{K}),, inject(12)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(50)(.List{K}),, inject(12)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(51)(.List{K}),, inject(12)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(52)(.List{K}),, inject(12)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(53)(.List{K}),, inject(12)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(54)(.List{K}),, inject(12)(.List{K})) |-> inject("4")(.List{K})
	coord(inject(55)(.List{K}),, inject(12)(.List{K})) |-> inject("+")(.List{K})
	coord(inject(56)(.List{K}),, inject(12)(.List{K})) |-> inject("1")(.List{K})
	coord(inject(57)(.List{K}),, inject(12)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(58)(.List{K}),, inject(12)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(49)(.List{K}),, inject(13)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(13)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(51)(.List{K}),, inject(13)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(52)(.List{K}),, inject(13)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(53)(.List{K}),, inject(13)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(54)(.List{K}),, inject(13)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(3)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(4)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(5)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(6)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(7)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(8)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(9)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(10)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(11)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(12)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(13)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(14)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(15)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(16)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(17)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(18)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(19)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(20)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(21)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(22)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(23)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(24)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(25)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(26)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(27)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(28)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(29)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(30)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(31)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(32)(.List{K}),, inject(14)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(33)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(14)(.List{K})) |-> inject("^")(.List{K})
	coord(inject(49)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(51)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(53)(.List{K}),, inject(14)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(54)(.List{K}),, inject(14)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(55)(.List{K}),, inject(14)(.List{K})) |-> inject("5")(.List{K})
	coord(inject(56)(.List{K}),, inject(14)(.List{K})) |-> inject("4")(.List{K})
	coord(inject(57)(.List{K}),, inject(14)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(58)(.List{K}),, inject(14)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(59)(.List{K}),, inject(14)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(15)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(15)(.List{K})) |-> inject("F")(.List{K})
	coord(inject(3)(.List{K}),, inject(15)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(4)(.List{K}),, inject(15)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(5)(.List{K}),, inject(15)(.List{K})) |-> inject("g")(.List{K})
	coord(inject(6)(.List{K}),, inject(15)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(7)(.List{K}),, inject(15)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(15)(.List{K})) |-> inject("b")(.List{K})
	coord(inject(10)(.List{K}),, inject(15)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(11)(.List{K}),, inject(15)(.List{K})) |-> inject("3")(.List{K})
	coord(inject(12)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(15)(.List{K})) |-> inject("m")(.List{K})
	coord(inject(14)(.List{K}),, inject(15)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(15)(.List{K}),, inject(15)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(16)(.List{K}),, inject(15)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(17)(.List{K}),, inject(15)(.List{K})) |-> inject("l")(.List{K})
	coord(inject(18)(.List{K}),, inject(15)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(19)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(15)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(29)(.List{K}),, inject(15)(.List{K})) |-> inject("U")(.List{K})
	coord(inject(30)(.List{K}),, inject(15)(.List{K})) |-> inject("N")(.List{K})
	coord(inject(31)(.List{K}),, inject(15)(.List{K})) |-> inject("E")(.List{K})
	coord(inject(32)(.List{K}),, inject(15)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(33)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(35)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(15)(.List{K})) |-> inject("^")(.List{K})
	coord(inject(49)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(51)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(53)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(54)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(55)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(58)(.List{K}),, inject(15)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(59)(.List{K}),, inject(15)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(60)(.List{K}),, inject(15)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(0)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(16)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(16)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(33)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(16)(.List{K})) |-> inject("v")(.List{K})
	coord(inject(35)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(16)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(46)(.List{K}),, inject(16)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(47)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(16)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(49)(.List{K}),, inject(16)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(50)(.List{K}),, inject(16)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(51)(.List{K}),, inject(16)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(52)(.List{K}),, inject(16)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(53)(.List{K}),, inject(16)(.List{K})) |-> inject("\"")(.List{K})
	coord(inject(54)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(55)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(58)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(59)(.List{K}),, inject(16)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(60)(.List{K}),, inject(16)(.List{K})) |-> inject("<")(.List{K})
	coord(inject(0)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(17)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(17)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(17)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(17)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(17)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(17)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(17)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(17)(.List{K})) |-> inject("`")(.List{K})
	coord(inject(10)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(17)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(12)(.List{K}),, inject(17)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(13)(.List{K}),, inject(17)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(14)(.List{K}),, inject(17)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(15)(.List{K}),, inject(17)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(16)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(17)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(17)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(18)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(18)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(18)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(18)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(18)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(18)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(18)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(18)(.List{K})) |-> inject(":")(.List{K})
	coord(inject(10)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(18)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(12)(.List{K}),, inject(18)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(13)(.List{K}),, inject(18)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(14)(.List{K}),, inject(18)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(15)(.List{K}),, inject(18)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(16)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(18)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(18)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(19)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(19)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(19)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(19)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(19)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(19)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(19)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(19)(.List{K})) |-> inject("0")(.List{K})
	coord(inject(10)(.List{K}),, inject(19)(.List{K})) |-> inject("-")(.List{K})
	coord(inject(11)(.List{K}),, inject(19)(.List{K})) |-> inject("9")(.List{K})
	coord(inject(12)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(19)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(14)(.List{K}),, inject(19)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(15)(.List{K}),, inject(19)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(16)(.List{K}),, inject(19)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(17)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(19)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(19)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(20)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(20)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(20)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(20)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(20)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(20)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(20)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(20)(.List{K})) |-> inject("$")(.List{K})
	coord(inject(10)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(20)(.List{K})) |-> inject("w")(.List{K})
	coord(inject(12)(.List{K}),, inject(20)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(13)(.List{K}),, inject(20)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(14)(.List{K}),, inject(20)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(15)(.List{K}),, inject(20)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(16)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(20)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(20)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(21)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(21)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(21)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(21)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(21)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(21)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(21)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(21)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(10)(.List{K}),, inject(21)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(11)(.List{K}),, inject(21)(.List{K})) |-> inject("g")(.List{K})
	coord(inject(12)(.List{K}),, inject(21)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(13)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(21)(.List{K})) |-> inject("j")(.List{K})
	coord(inject(15)(.List{K}),, inject(21)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(16)(.List{K}),, inject(21)(.List{K})) |-> inject("m")(.List{K})
	coord(inject(17)(.List{K}),, inject(21)(.List{K})) |-> inject("p")(.List{K})
	coord(inject(18)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(21)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(20)(.List{K}),, inject(21)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(21)(.List{K}),, inject(21)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(22)(.List{K}),, inject(21)(.List{K})) |-> inject("u")(.List{K})
	coord(inject(23)(.List{K}),, inject(21)(.List{K})) |-> inject("r")(.List{K})
	coord(inject(24)(.List{K}),, inject(21)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(25)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(21)(.List{K})) |-> inject("p")(.List{K})
	coord(inject(27)(.List{K}),, inject(21)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(28)(.List{K}),, inject(21)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(29)(.List{K}),, inject(21)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(30)(.List{K}),, inject(21)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(31)(.List{K}),, inject(21)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(21)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(22)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(22)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(22)(.List{K})) |-> inject("C")(.List{K})
	coord(inject(3)(.List{K}),, inject(22)(.List{K})) |-> inject("h")(.List{K})
	coord(inject(4)(.List{K}),, inject(22)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(5)(.List{K}),, inject(22)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(6)(.List{K}),, inject(22)(.List{K})) |-> inject("k")(.List{K})
	coord(inject(7)(.List{K}),, inject(22)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(8)(.List{K}),, inject(22)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(22)(.List{K})) |-> inject("!")(.List{K})
	coord(inject(10)(.List{K}),, inject(22)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(22)(.List{K})) |-> inject("d")(.List{K})
	coord(inject(12)(.List{K}),, inject(22)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(13)(.List{K}),, inject(22)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(14)(.List{K}),, inject(22)(.List{K})) |-> inject("s")(.List{K})
	coord(inject(15)(.List{K}),, inject(22)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(22)(.List{K})) |-> inject("l")(.List{K})
	coord(inject(17)(.List{K}),, inject(22)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(18)(.List{K}),, inject(22)(.List{K})) |-> inject("g")(.List{K})
	coord(inject(19)(.List{K}),, inject(22)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(20)(.List{K}),, inject(22)(.List{K})) |-> inject("c")(.List{K})
	coord(inject(21)(.List{K}),, inject(22)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(22)(.List{K}),, inject(22)(.List{K})) |-> inject("l")(.List{K})
	coord(inject(23)(.List{K}),, inject(22)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(22)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(25)(.List{K}),, inject(22)(.List{K})) |-> inject("e")(.List{K})
	coord(inject(26)(.List{K}),, inject(22)(.List{K})) |-> inject("g")(.List{K})
	coord(inject(27)(.List{K}),, inject(22)(.List{K})) |-> inject("a")(.List{K})
	coord(inject(28)(.List{K}),, inject(22)(.List{K})) |-> inject("t")(.List{K})
	coord(inject(29)(.List{K}),, inject(22)(.List{K})) |-> inject("i")(.List{K})
	coord(inject(30)(.List{K}),, inject(22)(.List{K})) |-> inject("o")(.List{K})
	coord(inject(31)(.List{K}),, inject(22)(.List{K})) |-> inject("n")(.List{K})
	coord(inject(32)(.List{K}),, inject(22)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(23)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(2)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(3)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(4)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(5)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(6)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(7)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(8)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(9)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(10)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(11)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(12)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(13)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(14)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(15)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(16)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(17)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(18)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(19)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(20)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(21)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(22)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(23)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(24)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(25)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(26)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(27)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(28)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(29)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(30)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(31)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(32)(.List{K}),, inject(23)(.List{K})) |-> inject(";")(.List{K})
	coord(inject(0)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(1)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(2)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(3)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(4)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(5)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(6)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(7)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(8)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(9)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(10)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(11)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(12)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(13)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(14)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(15)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(16)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(17)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(18)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(19)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(20)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(21)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(22)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(23)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(24)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(25)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(26)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(27)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(28)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(29)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(30)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(31)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(32)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(33)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(34)(.List{K}),, inject(24)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(35)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(36)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(37)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(38)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(39)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(40)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(41)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(42)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(43)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(44)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(45)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(46)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(47)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(48)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(49)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(50)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(51)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(52)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(53)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(54)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(55)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(56)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(57)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(58)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(59)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(60)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(61)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(62)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(63)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(64)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(65)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(66)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(67)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(68)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(69)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(70)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(71)(.List{K}),, inject(24)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(72)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(73)(.List{K}),, inject(24)(.List{K})) |-> inject(">")(.List{K})
	coord(inject(74)(.List{K}),, inject(24)(.List{K})) |-> inject(":")(.List{K})
	coord(inject(75)(.List{K}),, inject(24)(.List{K})) |-> inject("#")(.List{K})
	coord(inject(76)(.List{K}),, inject(24)(.List{K})) |-> inject(",")(.List{K})
	coord(inject(77)(.List{K}),, inject(24)(.List{K})) |-> inject("_")(.List{K})
	coord(inject(78)(.List{K}),, inject(24)(.List{K})) |-> inject(" ")(.List{K})
	coord(inject(79)(.List{K}),, inject(24)(.List{K})) |-> inject("@")(.List{K})
))) .
endm

---set trace on .
rew eval(pB93(.List{K})) .
