
# this is the name of the main maude module 
 LANGUAGE_NAME = TEST
# LANGUAGE_NAME = OCL-SYNTAX

# this are all interesting modules (used to latexify)
#LANGUAGE_MODULES = 

LATEX_STYLE = bb

# this is the basename of the main file
# MAIN_FILE = ocl-syntax
 MAIN_FILE = ocl-semantics

# these are additional files that when changed will force rebuilding the semantics
#ADDITIONAL_DEPENDENCIES = 

# this is a space-separated list of basename maude files to run
#TESTS =  

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk

