DEF=test
EXT=test
TESTDIR=.
KOMPILE_BACKEND=haskell # llvm backend does not support mint yet so we test only the frontend for now
KOMPILE_FLAGS=--syntax-module TEST

include ../../../include/kframework/ktest.mak
