#!/usr/bin/env bash

for test_list in inset union diff intersect; do
    i=1
    while read line; do
        spec_file="$test_list-$i-spec.k"
        module_name="$(echo $test_list | tr '[:lower:]' '[:upper:]')"
        if [[ -n "$line" ]] && [[ ! -f "$spec_file" ]] && [[ ! -f "failing/$spec_file" ]]; then
            {   echo "// Copyright (c) 2022 K Team. All Rights Reserved."
                echo "// generated by gen-tests.sh"
                echo ""
                echo "requires \"set-tests.k\""
                echo ""
                echo "module $module_name-$i-SPEC"
                echo "    imports SET-TESTS"
                echo ""
                echo "    $line"
                echo ""
                echo "endmodule"
            } > $spec_file
            make CHECK='> ' $spec_file
        fi
        i=$((i + 1))
    done < $test_list
done
