load ../../../../../../../../k-prelude
load imp++-syntax
--- resolving Builtins subsorted to K into injections
---(
load ../../../../../../../../tools/subsorts-to-wrappers-interface
---(
set print attribute on .
red in SUBSORTS-TO-WRAPPERS-META : resolveKSubsorts('IMP++-SYNTAX, '0SUBSORTS) .
q
---)
loop subsorts-to-wrappers .
(resolveKSubsorts IMP++-SYNTAX 0 .)
q
---)

load imp++-programs

--- resolving Builtins subsorted to K into injections
---(
load ../imp++-syntax
load ../../../../../../../../tools/subsorts-to-wrappers-interface

---(
set print attribute on .
red in SUBSORTS-TO-WRAPPERS-META : resolveKSubsorts('IMP++-PROGRAMS, '0SUBSORTS) .
q
---)
loop subsorts-to-wrappers .
(resolveKSubsorts IMP++-PROGRAMS 0 .)
q
---)
load imp++-semantics

--- resolving Builtins subsorted to K into injections
---()
load ../imp++-syntax
load ../../../../../../../../tools/subsorts-to-wrappers-interface
---(
set print attribute on .
red in SUBSORTS-TO-WRAPPERS-META : resolveKSubsorts('IMP++-SEMANTICS, '0) .
q
---)
loop subsorts-to-wrappers .
(resolveKSubsorts IMP++-SEMANTICS 0 .)
q
---()
