load ../../../../../../../../../../k-prelude
load ../../../imp++-syntax
load ../../../imp++-programs
load imp++-semantics
---()
load ../../../../../../../../../../tools/context-transformers-interface
---(
set print attribute on .
red in  CONTEXT-TRANSFORMERS-META : resolveKCxt("IMP++-SEMANTICS-K-PROPER","IMP++-SEMANTICS-K-PROPER","IMP++-SEMANTICS-K-PROPER") .
q
---)
loop context-transformers .
(resolveKCxt IMP++-SEMANTICS-K-PROPER IMP++-SEMANTICS-K-PROPER IMP++-SEMANTICS-K-PROPER .)
q
---()

