DEF=test
EXT=test
TESTDIR=.
KOMPILE_BACKEND=llvm
BENCHMARK_NAME=AVM-SEMANTICS
KOMPILE_FLAGS=--main-module AVM-TESTING --syntax-module AVM-TESTING-SYNTAX

include ../../../include/kframework/ktest.mak
