// Copyright (c) 2014-2015 K Team. All Rights Reserved.
//require "modules/verification_lemmas.k"
require "domains.k"
require "kernelc-syntax.k"
require "kernelc-semantics.k"
require "patterns/int_set.k"
require "patterns/int_list.k"
require "patterns/list_pattern.k"
require "patterns/tree_pattern.k"
//require "tests/cd2d/cdd_spec_aux.k"

module KERNELC
  imports KERNELC-SEMANTICS
  imports LIST-PATTERN
  imports TREE-PATTERN
  //imports VERIFICATION_LEMMAS
  //imports CDD-SPEC-AUX
endmodule
