// Copyright (c) 2014-2019 K Team. All Rights Reserved.
package org.kframework.parser.outer;

import java.util.List;

import junit.framework.Assert;

import org.junit.Test;
import org.kframework.attributes.Source;
import org.kframework.kil.DefinitionItem;
import org.kframework.kil.Lexical;
import org.kframework.kil.Module;
import org.kframework.kil.StringSentence;
import org.kframework.kil.Syntax;

public class OuterParsingTests {

    @Test
    public void testEmptyRules() throws Exception {
        // TODO: remove once the new parser is fully functional
        String def = "module TEST rule endmodule";

        List<DefinitionItem> defItemList = Outer.parse(Source.apply("generated by OuterParsingTests"), def, null);

        Module mod = (Module) defItemList.get(0);
        StringSentence sen = (StringSentence) mod.getItems().get(0);
        Assert.assertEquals(sen.getContent(), "");
    }
}
