
# this is the name of the main maude module  (hack!!! -lib)
LANGUAGE_NAME = XSPEM  -lib values

# the interesting modules we want to visualize
LANGUAGE_MODULES = OCL-SYNTAX OCL-SEMANTICS

LATEX_STYLE = bubble
# LATEX_TOPMATTER = README.tex

#this is the basename of the main file
MAIN_FILE = XSPEM

# this is a space-separated list of basename maude files to run
TESTS = test.maude

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
