---- Syntactic structures that exist in Haskell
mod HASKELL-SYNTAX-STRUCTS is
  including K .

  --- Parameterized sorts are a lot of trouble in Maude, so here's some monosorted versions of haskell constructs
  sorts HsMaybe HsList HsTuple .

  op emptyList :	     -> HsList [ctor] .
  op _ :: _ : K HsList -> HsList [ctor] .

  op Just _ : K	 -> HsMaybe [ctor] .
  op Nothing :   -> HsMaybe [ctor] .

  op mkTuple : List{K} -> HsTuple [ctor] .

  subsorts HsList HsMaybe HsTuple < K .

endm
