#!/usr/bin/env zsh
# Tool to load up all the kaskell files and launch maude in interpretive mode


# Get the directory of this script (works even in Mac OSX)
SCRIPT_DIR=$(
cd -P -- "$(dirname -- "$0")" &&
printf '%s\n' "$(pwd -P)/$(basename -- "$0")"
) || exit 1
SCRIPT_DIR=`dirname "$SCRIPT_DIR"`

K_ROOT="$SCRIPT_DIR/../../../../"

pushd $SCRIPT_DIR

HASKELL_SOURCES=(hsStructs.maude haskell-syntax.maude translations.maude runner.maude)

rlwrap -a -pcyan maude -no-banner -no-wrap "$K_ROOT/k-prelude.maude" $HASKELL_SOURCES

popd $SCRIPT_DIR
