#!/usr/bin/env zsh

# Get the directory of this script (works even in Mac OSX)
SCRIPT_DIR=$(
cd -P -- "$(dirname -- "$0")" &&
printf '%s\n' "$(pwd -P)/$(basename -- "$0")"
) || exit 1
SCRIPT_DIR=`dirname "$SCRIPT_DIR"`

K_ROOT="$SCRIPT_DIR/../../../../"

pushd $SCRIPT_DIR
echo maude "$K_ROOT/k-prelude.maude" hsStructs.maude haskell-syntax.maude
maude "$K_ROOT/k-prelude.maude" hsStructs.maude haskell-syntax.maude
popd $SCRIPT_DIR