DEF=test
EXT=test
TESTDIR=.
KOMPILE_BACKEND=llvm
KOMPILE_FLAGS+=--enable-search --syntax-module TEST
KRUN_FLAGS+=--search-final --no-pattern

include /home/robertorosmaninho/rv/k/k-distribution/include/kframework/ktest.mak
