# this is the name of the main maude module 
LANGUAGE_NAME = GHC-CORE-TEST

#this is the basename of the main file
MAIN_FILE = ghc-core-test

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
