name: 'Build and Test Package'
description: 'Build the package for a given distribution and test it.'
inputs:
  distro:
    description: 'Distribution to build and test package for.'
    required: true
  llvm:
    description: 'LLVM version to use.'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Check out code'
    uses: actions/checkout@v3
    with:
      path: k-${{ inputs.distro }}
      submodules: recursive
  - name: 'Set up Docker'
    uses: ./.github/actions/with-docker
    with:
      tag: k-package-build-${{ inputs.distro }}
      subdir: k-${{ inputs.distro }}/
      distro: ${{ inputs.distro }}
      llvm: ${{ inputs.llvm }}
  - name: 'Build Package: ${{ inputs.distro }}'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    run: |
      set -euxo pipefail
      docker exec -t k-package-build-${DISTRO} /bin/bash -c 'mv package/debian debian'
      docker exec -t k-package-build-${DISTRO} /bin/bash -c 'mv debian/compat.jammy debian/compat'
      docker exec -t k-package-build-${DISTRO} /bin/bash -c 'mv debian/control.jammy debian/control'
      docker exec -t k-package-build-${DISTRO} /bin/bash -c 'mv debian/rules.jammy debian/rules'
      docker exec -t k-package-build-${DISTRO} /bin/bash -c 'dpkg-buildpackage'
  - name: 'Tear down Docker'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    if: always()
    run: |
      docker stop --time=0 k-package-build-${DISTRO}
      docker container rm --force k-package-build-${DISTRO} || true
  - name: 'Set up Docker Test Image: ${{ inputs.distro }}'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    run: |
      set -euxo pipefail
      workspace=$(pwd)
      cd k-${DISTRO}
      docker run                         \
        --name k-package-test-${DISTRO}  \
        --rm -it                         \
        --detach                         \
        --workdir /opt/workspace         \
        -v ${HOME}:${HOME}               \
        -v "${workspace}:/opt/workspace" \
        -v "/etc/passwd:/etc/passwd:ro"  \
        -v "/etc/group:/etc/group:ro"    \
        ubuntu:${DISTRO}
  - name: 'Test Package: ${{ inputs.distro }}'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    run: |
      set -euxo pipefail
      docker exec -t k-package-test-${DISTRO} /bin/bash -c "k-${DISTRO}/src/main/scripts/test-in-container-debian"
  - name: 'Tear down Docker Test'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    if: always()
    run: |
      docker stop --time=0 k-package-test-${DISTRO}
      docker container rm --force k-package-test-${DISTRO} || true
  - name: 'Rename Package'
    shell: bash {0}
    env:
      DISTRO: ${{ inputs.distro }}
    run: mv kframework_$(cat package/version)_amd64.deb kframework_amd64_${DISTRO}.deb
