
# this is the name of the main maude module 
LANGUAGE_NAME = EXP-UNTYPED-SUBSTITUTION

# this are all interesting modules (used to latexify)
#LANGUAGE_MODULES = 

#this is the basename of the main file
MAIN_FILE = exp-untyped-substitution

# this is a space separated list of directories containing io_tests
IO_TESTS = regression/tests
# this is the name the tests will be grouped under
IO_TESTSUITE_NAME = $(MAIN_FILE)
# this is a flag used when calling krun to be used when doing io_tests
IO_TEST_FLAG = "--no-color"

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
