// Copyright (c) 2014-2015 K Team. All Rights Reserved.

package org.kframework.kore.convertors;

import junit.framework.Assert;
import org.junit.Test;
import org.junit.rules.TestName;
import org.kframework.attributes.Source;
import org.kframework.definition.Module;
import org.kframework.kore.K;
import org.kframework.kore.Kompile;
import org.kframework.tiny.Rewriter;
import scala.Tuple2;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.function.BiFunction;


public class TstTinyOnKORE_IT {


    @org.junit.Rule
    public TestName name = new TestName();


    protected File testResource(String baseName) throws URISyntaxException {
        return new File(TstTinyOnKORE_IT.class.getResource(baseName).toURI());
    }

    @Test
    public void kore_imp_tiny() throws IOException, URISyntaxException {

        String filename = "/convertor-tests/" + name.getMethodName() + ".k";

        File definitionFile = testResource(filename);
        Tuple2<Module, BiFunction<String, Source, K>> rwModuleAndProgramParser = new Kompile().getStuff(definitionFile, "TEST", "TEST-PROGRAMS");

        Module module = rwModuleAndProgramParser._1();
        BiFunction<String, Source, K> programParser = rwModuleAndProgramParser._2();
        Rewriter rewriter = Kompile.getRewriter(module);

        K program = programParser.apply(
                "<top><k> while(0<=n) { s = s + n; n = n + -1; } </k><state>n|->10 s|->0</state></top>", Source.apply("generated by " + getClass().getSimpleName()));

        long l = System.nanoTime();
        K result = rewriter.execute(program);
        System.out.println("time = " + (System.nanoTime() - l) / 1000000);

        System.out.println("result = " + result.toString());

        Assert.assertEquals("<top>(<k>(#KSequence()),<state>(_Map_(Tuple2(s:Id,55),Tuple2(n:Id,-1))))", result.toString());
    }

}
