#!/usr/bin/env bash

set -euxo pipefail

base_distro="$1" ; shift
subdir="$1" ; shift
pkg_name="$1" ; shift

mkdir debian

mv package/debian/${subdir}/changelog               debian/changelog
mv package/debian/${subdir}/copyright               debian/copyright
mv package/debian/${subdir}/${subdir}-docs.docs     debian/${subdir}-docs.docs
mv package/debian/${subdir}/source                  debian/source

mv package/debian/${subdir}/compat.${base_distro}   debian/compat
mv package/debian/${subdir}/control.${base_distro}  debian/control
mv package/debian/${subdir}/rules.${base_distro}    debian/rules

dpkg-buildpackage

# The .deb filename uses the Debian package version from debian/changelog, which can
# differ from package/version; glob the artifact dpkg actually produced.
shopt -s nullglob
matches=(../"${subdir}"_*_amd64.deb)
if [ "${#matches[@]}" -eq 0 ]; then
  echo "error: no ../${subdir}_*_amd64.deb after dpkg-buildpackage" >&2
  exit 1
fi
if [ "${#matches[@]}" -gt 1 ]; then
  echo "error: expected one ../${subdir}_*_amd64.deb, got: ${matches[*]}" >&2
  exit 1
fi
mv "${matches[0]}" "${pkg_name}"
