#!/bin/sh -ex

pkg="$1" ; shift

K_VERSION=5.5.0

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade --yes
apt-get install --yes make
apt-get install --yes "${pkg}"

"$(dirname "$0")/test-in-container"
