// Copyright (c) 2014-2015 K Team. All Rights Reserved.
package org.kframework.kil;

public class GeneratedSource implements Source {
    private Class<?> sourceClass;

    private String simpleName;

    public GeneratedSource(Class<?> sourceClass) {
        this.sourceClass = sourceClass;
        simpleName = sourceClass.getSimpleName();
    }

    public Class<?> getSourceClass() {
        return sourceClass;
    }

    @Override
    public String toString() {
        return "Generated by " + simpleName;
    }

    @Override
    public int hashCode() {
        return simpleName.hashCode();
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Source)) {
            return false;
        }
        Source s = (Source) o;
        return simpleName.equals(s.toString());
    }
}
