// Copyright (c) 2014-2015 K Team. All Rights Reserved.
package org.kframework.kil;

public class GeneratedSource implements Source {
    private Class<?> sourceClass;

    public GeneratedSource(Class<?> sourceClass) {
        this.sourceClass = sourceClass;
    }

    public Class<?> getSourceClass() {
        return sourceClass;
    }

    @Override
    public String toString() {
        return "Generated by " + sourceClass.getSimpleName();
    }
}
