// Copyright (c) 2014-2015 K Team. All Rights Reserved.
package org.kframework.kil;

public class GeneratedSource implements Source {
    private Class<?> sourceClass;

    private String simpleName;

    public GeneratedSource(Class<?> sourceClass) {
        this.sourceClass = sourceClass;
        simpleName = sourceClass.getSimpleName();
    }

    public Class<?> getSourceClass() {
        return sourceClass;
    }

    @Override
    public String toString() {
        return "Generated by " + simpleName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        GeneratedSource that = (GeneratedSource) o;

        if (!simpleName.equals(that.simpleName)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return simpleName.hashCode();
    }
}
