DEF=lambda
EXT=lambda
KOMPILE_FLAGS=--syntax-module LAMBDA
KOMPILE_BACKEND?=java
KRUN_FLAGS=--search --pattern "<tasks> <task> <k> T:Type </k> ...</task> </tasks>"

include ../../../../include/ktest.mak
