DEF=ceil-set
EXT=test
TESTDIR=.
KOMPILE_BACKEND=haskell
KPROVE_FLAGS=--warnings none
export KORE_EXEC_OPTS=--log-level error

include ../../../include/kframework/ktest.mak

KPROVE_OR_LEGACY=$(KPROVE)
CONSIDER_PROVER_ERRORS=2>&1
