/* Generated By:JavaCC: Do not edit this line. KastParserConstants.java */
package org.kframework.utils.kastparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KastParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KSEQ = 5;
  /** RegularExpression Id. */
  int DOTK = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int DOTKLIST = 10;
  /** RegularExpression Id. */
  int TOKENLABEL = 11;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int KLABEL = 21;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;
  /** Lexical state. */
  int KLABEL_STATE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"~>\"",
    "\".K\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".KList\"",
    "\"#token\"",
    "\"\\\"\"",
    "<token of kind 13>",
    "<token of kind 14>",
    "<token of kind 15>",
    "<token of kind 16>",
    "<token of kind 17>",
    "\"\\\"\"",
    "<token of kind 19>",
    "<token of kind 20>",
    "\"(\"",
  };

}
