
# this is the name of the main maude module 
LANGUAGE_NAME = EXP-UNTYPED

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = EXP-SYNTAX EXP-UNTYPED-DESUGARED-SYNTAX EXP-UNTYPED-SEMANTICS

#this is the basename of the main file
MAIN_FILE = exp-untyped

# this is a space-separated list of basename maude files to run
TESTS = exp-untyped-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
