DEF=deposit-symbolic
EXT=deposit
TESTDIR=.
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--syntax-module DEPOSIT-SYMBOLIC
KPROVE_FLAGS=--smt-prelude imap.smt2

include ../../../../../include/kframework/ktest.mak
