DEF=deposit-symbolic
EXT=deposit
TESTDIR=.
KOMPILE_BACKEND=java
KOMPILE_FLAGS=--syntax-module DEPOSIT-SYMBOLIC
KPROVE_FLAGS=--smt-prelude imap.smt2

# This test is disabled until https://github.com/kframework/k/issues/2308 is
# resolved; the SMT solver behaviour needed to implement this test correctly is
# not available until partial hooks can be defined.

disable:

clean:

# include ../../../../../include/kframework/ktest.mak
