--- in ../../../k-prelude
--- in simp-syntax

mod SIMP-MC-PROGRAMS is including SIMP-SYNTAX + PL-INT .

  ops a b c d e f g h i j k l m n o p q r s t u v w x y z err : -> Id .
  op pTest : -> Stmts .


  eq pTest =
       var x ; var y ;  var err ;

       x = 0 ;
       err = x ;
       while ( y <= 0 ) do {
         x = x + 1 ;
	 y = y + x ;
	 x = -1 + x ;
	 if not ( x == 0 ) then { err = 1 ; } else { skip; }
       }
 .

endm
