
# this is the name of the main maude module 
LANGUAGE_NAME = BF

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = BF

#this is the basename of the main file
MAIN_FILE = bf

LATEX_STYLE = bb
LATEX_TOPMATTER = topmatter.tex

# this is a space-separated list of basename maude files to run
TESTS = test.maude

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
