
# this is the name of the main maude module 
LANGUAGE_NAME = QUOTE-UNQUOTE-TEST

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = QUOTE-UNQUOTE

#this is the basename of the main file
MAIN_FILE = quote-unquote-test

# this is a space-separated list of basename maude files to run
TESTS = test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
