in /modules/basic-run
in /modules/k-visitor
in /modules/quote-unquote

load ../ids
in /modules/exp
in /modules/if
in /modules/substitution
in /modules/lambda
in /modules/mu
in /modules/seq
in /modules/ref
in /modules/io
in /modules/while
load programs

kmod RUN is including QUOTE-UNQUOTE-PROGRAMS + BASIC-RUN 
  configuration <T><k> .K </k> <nextId>0</nextId> <mem>.Map</mem> <nextLoc>0</nextLoc><in>.List</in><out>.List</out></T>
endkm
