DEF=domains-lemmas-no-smt
EXT=dlns
TESTDIR=.
KOMPILE_BACKEND=haskell
KPROVE_FLAGS=--def-module DOMAINS-LEMMAS-NO-SMT --smt none
KOMPILE_FLAGS=--syntax-module TEST

include ../../../include/kframework/ktest.mak
