DEF=main
EXT=a
TESTDIR=.
RESULTDIR=.

KOMPILE_FLAGS=--syntax-module MAIN
KOMPILE_BACKEND?=java

KPROVE_FLAGS=--boundary-cells k,unused --def-module VERIFICATION

include ../../../include/kframework/ktest.mak
