
# this is the name of the main maude module 
LANGUAGE_NAME = IMPPP

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES =

# include the contents of this file right after \begin{document}
LATEX_TOPMATTER =

#this is the basename of the main file
MAIN_FILE = imppp

# this is a space-separated list of basename maude files to run
TESTS = 

# this is a space separated list of directories containing io_tests
IO_TESTS = programs/tests
# this is the name the tests will be grouped under
IO_TESTSUITE_NAME = $(MAIN_FILE)
# this is a flag used when calling krun to be used when doing io_tests
IO_TEST_FLAG = "--no-color --output-mode=none"

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
