
# this is the name of the main maude module 
LANGUAGE_NAME = IMPPP

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = IMPPP-SYNTAX IMPPP-CONFIGURATION IMPPP-SEMANTICS IMPPP

#this is the basename of the main file
MAIN_FILE = imppp

# this is a space-separated list of basename maude files to run
TESTS = imppp-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
