DEF=imp
EXT=imp
TESTDIR=.
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--post-process 'cat'
KPROVE_FLAGS=
export KOMPILE_BACKEND
export KPROVE_FLAGS
export KORE_EXEC_OPTS=--log-level error

include ../include/ktest.mak
