DEF=domains-lemmas-no-smt
EXT=dlns
TESTDIR=.
KOMPILE_BACKEND=haskell
KPROVE_FLAGS=--smt none
KOMPILE_FLAGS=--syntax-module DOMAINS-LEMMAS-NO-SMT
export KORE_EXEC_OPTS=--log-level error

include ../include/ktest.mak
