
# this is the name of the main maude module 
LANGUAGE_NAME = ISSUE152

# this is the name of the interesting modules (used by make latex/pdf) 
LANGUAGE_MODULES = ISSUE152

#this is the basename of the main file
MAIN_FILE = issue152

# this is a space-separated list of basename maude files to run
TESTS = test.m

TOOL_DIR =  $(K_CORE)/../tools/
include $(TOOL_DIR)make-helper.mk
