DEF=test
TESTDIR=.
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--syntax-module TEST --concrete-rules SERIALIZATION.keccak
export KORE_EXEC_OPTS=--log-level error

include ../include/ktest.mak

CONSIDER_PROVER_ERRORS=2>&1
