#!/usr/bin/env perl

# Eliminates all K comments from the passed files and prints the combined
# result at stdout.  This is useful when you want to focus on the semantic
# definition itself and the comments stay in the way, or when you want to
# see how big an actual K definition is.


foreach (@ARGV) {
    kpp($_);
}

sub kpp {
    my ($filename) = @_;
    open FILEHANDLE, "<", $filename or die "Could not open $filename:\n$!";
    $_ = join("",<FILEHANDLE>);
    close FILEHANDLE;
    s|/\*(.*?)\*/\s*\n||gms;
    s|^\s*//(.*?)\n||gms;
    s|^\s*\n^\s*\n|\n|gms;
    print $_,"\n";
}
