DEF=$(basename $@)
KOMPILED_DIR=$(DEF)-kompiled
KDEP_FLAGS= --remake-depend --output-definition OutputDirectoryTest/$(KOMPILED_DIR) --no-prelude

include ../../../../include/kframework/ktest-kdep.mak
