../../../../../tools/kompile.pl -verbose ../c.maude -l C -style mm -crop COMMON-SEMANTICS-ASSIGNMENT COMMON-SEMANTICS-IDENTIFIERS COMMON-SEMANTICS-ARRAY-SUBSCRIPTING MEMORY COMMON-SEMANTICS-GOTO COMMON-SEMANTICS-WHILE COMMON-C-STATEMENTS

# TEST-ARITH-SYNTAX MEMORY

#COMMON-C-SYNTAX COMMON-SEMANTIC-SYNTAX C-CONFIGURATION C-SETTINGS SEMANTIC-HELPERS COMMON-INCLUDE COMMON-PARAMETER-BINDING COMMON-GLOBAL-DECLARATION COMMON-LOCAL-DECLARATION MEMORY COMMON-SEMANTICS-PROMOTIONS COMMON-SEMANTICS-CAST COMMON-C-CONVERSIONS COMMON-SEMANTICS-TYPE-DECLARATIONS COMMON-SEMANTICS-EXPRESSIONS-INCLUDE COMMON-SEMANTICS-TYPE-STRICTNESS COMMON-C-TYPING COMMON-SEMANTICS-SIZEOF COMMON-SEMANTICS-IDENTIFIERS COMMON-SEMANTICS-FUNCTION-CALLS COMMON-SEMANTICS-ARRAY-SUBSCRIPTING COMMON-SEMANTICS-LITERALS COMMON-SEMANTICS-ASSIGNMENT COMMON-SEMANTICS-BITWISE COMMON-SEMANTICS-ARITHMETIC COMMON-SEMANTICS-MEMBERS COMMON-SEMANTICS-DEREFERENCE COMMON-SEMANTICS-REFERENCE COMMON-SEMANTICS-INCREMENT-AND-DECREMENT COMMON-C-EXPRESSIONS  COMMON-SEMANTICS-GOTO COMMON-SEMANTICS-IF-THEN COMMON-SEMANTICS-WHILE COMMON-SEMANTICS-SWITCH COMMON-SEMANTICS-RETURN COMMON-C-STATEMENTS COMMON-C-STANDARD-LIBRARY COMMON-C-SEMANTICS DYNAMIC-C-SEMANTICS C-SEMANTICS


# COMMON-C-STANDARD-LIBRARY 
# 
# pdflatex c.tex
