#../../../../../tools/kompile.pl -verbose ../c.maude -l C -style mm -crop COMMON-SEMANTICS-ASSIGNMENT COMMON-SEMANTICS-IDENTIFIERS COMMON-SEMANTICS-ARRAY-SUBSCRIPTING MEMORY COMMON-SEMANTICS-GOTO COMMON-SEMANTICS-WHILE COMMON-C-STATEMENTS

../../../../../tools/kompile.pl ../c.maude -l C -style mm -latex \
C-SEMANTICS \
COMMON-C-SYNTAX \
C-CONFIGURATION \
INCOMING-MODULES COMMON-SEMANTIC-SYNTAX C-SETTINGS SEMANTIC-HELPERS COMMON-INCLUDE \
COMMON-PARAMETER-BINDING COMMON-GLOBAL-DECLARATION COMMON-LOCAL-DECLARATION MEMORY \
COMMON-SEMANTICS-PROMOTIONS COMMON-SEMANTICS-CAST COMMON-C-CONVERSIONS \
COMMON-SEMANTICS-TYPE-DECLARATIONS COMMON-SEMANTICS-TYPE-STRICTNESS COMMON-C-TYPING \
COMMON-SEMANTICS-EXPRESSIONS-INCLUDE COMMON-SEMANTICS-SIZEOF COMMON-SEMANTICS-IDENTIFIERS COMMON-SEMANTICS-FUNCTION-CALLS COMMON-SEMANTICS-ARRAY-SUBSCRIPTING COMMON-SEMANTICS-LITERALS COMMON-SEMANTICS-ASSIGNMENT COMMON-SEMANTICS-BITWISE COMMON-SEMANTICS-ARITHMETIC COMMON-SEMANTICS-MEMBERS COMMON-SEMANTICS-DEREFERENCE COMMON-SEMANTICS-REFERENCE COMMON-SEMANTICS-INCREMENT-AND-DECREMENT COMMON-C-EXPRESSIONS \
COMMON-STATEMENTS-INCLUDE COMMON-SEMANTICS-IF-THEN COMMON-SEMANTICS-WHILE COMMON-SEMANTICS-SWITCH COMMON-SEMANTICS-GOTO COMMON-SEMANTICS-RETURN COMMON-C-STATEMENTS \
COMMON-C-STANDARD-LIBRARY \
COMMON-C-SEMANTICS \
DYNAMIC-C-SEMANTICS 

sed -i 's|../../../../../tools/}{|}{./|' c.tex
sed -i 's|}mybracket|}\\mybracket|' c.tex
sed -i 's|\\begin{document}|\\geometry{papersize={15in,8.5in},textwidth=14.75in,textheight=8in}\\begin{document}|' c.tex
pdflatex c.tex
