#!/usr/bin/env bash
curl -O ftp://ftp.strategoxt.org/pub/stratego/StrategoXT/strategoxt-0.17/aterm-2.5.tar.gz
curl -k -ssl3 -O https://svn.nixos.org/repos/nix/nixpkgs/trunk/pkgs/development/libraries/aterm/max-long.patch
tar xzf aterm-2.5.tar.gz
cd aterm-2.5/
patch -p1 < ../max-long.patch
./configure  --disable-shared --with-pic --prefix=`pwd`
make clean && make
make install
cd ..
curl -O ftp://ftp.strategoxt.org/pub/stratego/StrategoXT/strategoxt-0.17/sdf2-bundle-2.4.tar.gz
tar xzf sdf2-bundle-2.4.tar.gz
cd sdf2-bundle-2.4/
#this step requires pkg-config being installed on the system
./configure  --disable-shared --with-pic --prefix=`pwd` --with-aterm=`pwd`/../aterm-2.5
make clean && make
make install
cd ..
make
#copy src/sglr-server executable to the corresponding dist/lib/native directory
#cp src/sglr-server ../../dist/lib/native/...
