/*
 * The program below performs a read on an uninitialized integer variable,
 * which is undefined/unspecified according to the C standard.
 * gcc happily compiles this program and the resulting program prints 0.
 * If you check the error message generated by matchC, you can see that
 * matchC got stuck while attempting to print an undefined value.
 */


#include <stdio.h>


int main()
{
  int x;
  printf("%d", x);
}
