#COMPILE_OPTIONS = -supercool local -superheat nerd

# this is the name of the main maude module 
LANGUAGE_NAME = EXAMPLE

# this is the name of the interesting modules (used by make latex/pdf) 
LANGUAGE_MODULES = EXAMPLE

#this is the basename of the main file
MAIN_FILE = example

# this is a space-separated list of basename maude files to run
#TESTS = test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
