kompile 02_basics/README.md --md-selector "k & ! exclude" --main-module LESSON-02-A -d build/02a
kompile 02_basics/README.md --md-selector "k & ! exclude" --main-module LESSON-02-B -d build/02b
kompile 02_basics/README.md --md-selector "k & ! exclude" --main-module LESSON-02-C -d build/02c
kompile 02_basics/README.md --md-selector "k & ! exclude" --main-module LESSON-02-D -d build/02d
kompile 03_parsing/README.md --md-selector "k & ! exclude" --main-module LESSON-03-A -d build/03a
kompile 03_parsing/README.md --md-selector "k & ! exclude" --main-module LESSON-03-B -d build/03b
kompile 03_parsing/README.md --md-selector "k & ! exclude" --main-module LESSON-03-C -d build/03c
kompile 03_parsing/README.md --md-selector "k & ! exclude" --main-module LESSON-03-D -d build/03d --gen-bison-parser
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-A -d build/04a
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-B -d build/04b
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-C -d build/04c
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-D -d build/04d
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-E -d build/04e
kompile 04_disambiguation/README.md --md-selector "k & ! exclude" --main-module LESSON-04-F -d build/04f
kompile 05_modules/README.md --md-selector "k & ! exclude" --main-module LESSON-05-A -d build/05a
kompile 05_modules/README.md --md-selector "k & ! exclude" --main-module LESSON-05-B -d build/05b
kompile 05_modules/README.md --md-selector "k & ! exclude" --main-module LESSON-05-C -d build/05c
kompile 05_modules/README.md --md-selector "k & ! exclude" --main-module LESSON-05-D-2 -d build/05d
kompile 06_ints_and_bools/README.md --md-selector "k & ! exclude" --main-module LESSON-06-A -d build/06a
kompile 06_ints_and_bools/README.md --md-selector "k & ! exclude" --main-module LESSON-06-B -d build/06b
kompile 06_ints_and_bools/README.md --md-selector "k & ! exclude" --main-module LESSON-06-C -d build/06c
kompile 07_side_conditions/README.md --md-selector "k & ! exclude" --main-module LESSON-07-A -d build/07a
kompile 07_side_conditions/README.md --md-selector "k & ! exclude" --main-module LESSON-07-B -d build/07b
kompile 07_side_conditions/README.md --md-selector "k & ! exclude" --main-module LESSON-07-C -d build/07c
kompile 07_side_conditions/README.md --md-selector "k & ! exclude" --main-module LESSON-07-D -d build/07d
kompile 08_literate_programming/README.md --md-selector "k & ! exclude" --main-module LESSON-08 -d build/08
kompile 09_unparsing/README.md --md-selector "k & ! exclude" --main-module LESSON-09-A -d build/09a
kompile 09_unparsing/README.md --md-selector "k & ! exclude" --main-module LESSON-09-B -d build/09b
kompile 09_unparsing/README.md --md-selector "k & ! exclude" --main-module LESSON-09-C -d build/09c
kompile 10_strings/README.md --md-selector "k & ! exclude" --main-module LESSON-10 -d build/10
kompile 11_casts/README.md --md-selector "k & ! exclude" --main-module LESSON-11-A -d build/11a
kompile 11_casts/README.md --md-selector "k & ! exclude" --main-module LESSON-11-B -d build/11b
kompile 11_casts/README.md --md-selector "k & ! exclude" --main-module LESSON-11-C -d build/11c
kompile 11_casts/README.md --md-selector "k & ! exclude" --main-module LESSON-11-D -d build/11d
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-A -d build/12a
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-B -d build/12b
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-C -d build/12c
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-D -d build/12d
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-E -d build/12e
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-F -d build/12f
kompile 12_syntactic_lists/README.md --md-selector "k & ! exclude" --main-module LESSON-12-G -d build/12g
kompile 13_rewrite_rules/README.md --md-selector "k & ! exclude" --main-module LESSON-13-A -d build/13a
kompile 13_rewrite_rules/README.md --md-selector "k & ! exclude" --main-module LESSON-13-B -d build/13b
kompile 13_rewrite_rules/README.md --md-selector "k & ! exclude" --main-module LESSON-13-C -d build/13c
kompile 14_evaluation_order/README.md --md-selector "k & ! exclude & ! alias" --main-module LESSON-14-A -d build/14a
kompile 14_evaluation_order/README.md --md-selector "k & ! exclude & ! alias" --main-module LESSON-14-B -d build/14b
kompile 14_evaluation_order/README.md --md-selector "k & ! exclude" --main-module LESSON-14-C -d build/14c
kompile 14_evaluation_order/README.md --md-selector "k & ! exclude & ! alias" --main-module LESSON-14-D -d build/14d
kompile 15_configurations/README.md --md-selector "k & ! exclude" --main-module LESSON-15-A -d build/15a
kompile 15_configurations/README.md --md-selector "k & ! exclude" --main-module LESSON-15-B -d build/15b
kompile 15_configurations/README.md --md-selector "k & ! exclude" --main-module LESSON-15-C -d build/15c
kompile 16_collections/README.md --md-selector "k & ! exclude" --main-module LESSON-16-A -d build/16a
kompile 16_collections/README.md --md-selector "k & ! exclude" --main-module LESSON-16-B -d build/16b
kompile 16_collections/README.md --md-selector "k & ! exclude" --main-module LESSON-16-C -d build/16c
kompile 17_cell_multiplicity/README.md --md-selector "k & ! exclude" --main-module LESSON-17-A -d build/17a
kompile 17_cell_multiplicity/README.md --md-selector "k & ! exclude" --main-module LESSON-17-B -d build/17b
kompile 18_equality_and_conditionals/README.md --md-selector "k & ! exclude" --main-module LESSON-18 -d build/18
kompile 19_debugging/README.md --md-selector "k & ! exclude" --main-module LESSON-19-A -d build/19a
kompile 19_debugging/README.md --md-selector "k & ! exclude" --main-module LESSON-19-B -d build/19b
kompile 19_debugging/README.md --md-selector "k & ! exclude" --main-module LESSON-19-C -d build/19c
kompile 19_debugging/README.md --md-selector "k & ! exclude" --main-module LESSON-19-D -d build/19d
