../../../../tools/kompile.pl c.maude -l C -style bb -latex COMMON-C-SYNTAX C-CONFIGURATION C-SETTINGS SEMANTIC-HELPERS COMMON-INCLUDE COMMON-PARAMETER-BINDING COMMON-GLOBAL-DECLARATION COMMON-LOCAL-DECLARATION MEMORY COMMON-SEMANTICS-PROMOTIONS COMMON-SEMANTICS-CAST COMMON-C-CONVERSIONS COMMON-SEMANTICS-TYPE-DECLARATIONS COMMON-SEMANTICS-EXPRESSIONS-INCLUDE COMMON-SEMANTICS-TYPE-STRICTNESS COMMON-C-TYPING COMMON-SEMANTICS-SIZEOF COMMON-SEMANTICS-IDENTIFIERS COMMON-SEMANTICS-FUNCTION-CALLS COMMON-SEMANTICS-ARRAY-SUBSCRIPTING COMMON-SEMANTICS-LITERALS COMMON-SEMANTICS-ASSIGNMENT COMMON-SEMANTICS-BITWISE COMMON-SEMANTICS-ARITHMETIC COMMON-SEMANTICS-MEMBERS COMMON-SEMANTICS-DEREFERENCE COMMON-SEMANTICS-REFERENCE COMMON-C-EXPRESSIONS COMMON-SEMANTICS-IF-THEN COMMON-SEMANTICS-WHILE COMMON-SEMANTICS-SWITCH COMMON-SEMANTICS-RETURN COMMON-C-STATEMENTS COMMON-C-SEMANTICS DYNAMIC-C-SEMANTICS C-SEMANTICS

# COMMON-C-STANDARD-LIBRARY COMMON-SEMANTICS-GOTO COMMON-SEMANTICS-INCREMENT-AND-DECREMENT
# COMMON-SEMANTIC-SYNTAX

pdflatex c.tex
