DEF=imp
EXT=imp
TESTDIR=.
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--post-process 'cat'
KPROVE_FLAGS=--def-module VERIFICATION
export KOMPILE_BACKEND
export KPROVE_FLAGS

include ../../../include/kframework/ktest.mak
