
# this is the name of the main maude module 
LANGUAGE_NAME = SKOOL-TYPED-DYNAMIC

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = SKOOL-TYPED-SYNTAX SKOOL-TYPED-DYNAMIC-DESUGARED-SYNTAX SKOOL-TYPED-DYNAMIC-SEMANTICS SKOOL-TYPED-DYNAMIC

LATEX_STYLE = bubble

#this is the basename of the main file
MAIN_FILE = skool-typed-dynamic


# this is a space-separated list of basename maude files to run
TESTS = skool-typed-dynamic-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk

