DEF=demo
EXT=demo
TESTDIR=.
KOMPILE_BACKEND=java
KOMPILE_FLAGS=--syntax-module DEMO
KPROVE_FLAGS=--def-module VERIFICATION

CONSIDER_PROVER_ERRORS=2>&1

export KOMPILE_BACKEND
export KPROVE_FLAGS

include ../../../include/kframework/ktest.mak
