mod IMP++-SYNTAX is 
  including PL-INT .
  including K .
  sort VarId .
  subsort VarId < K .
  subsort Int < KResult .
  op _+_ : K K -> K [prec 33 gather (E e) format (d b o d) metadata "strict"] .
  op _/_ : K K -> K [prec 31 gather (E e) format (d b o d) metadata "strict"] .
  op ++_ : K -> K [prec 30 format (b o d)] .
--- BExp
  subsort Bool < KResult .
  op _<=_ : K K -> K  [prec 37 metadata "seqstrict" format (d b o d)] .
  op not_ : K -> K [prec 53 metadata "strict" format (b o d)] .
  op _and_ : K K -> K [prec 55 metadata "strict(1)" format (d b o d)] .
--- Stmt
  op skip : -> K [format (b o)] .
  op _:=_ : VarId K -> K [prec 40 metadata "strict(2)" format (d b o d)] .
  op _;_ : K K -> K [prec 122 gather (e E) format (d b noi d)] .
  op if_then_else_ : K K K -> K [prec 59 metadata "strict(1)" format (b o bni n++i bn--i n++i --)] .
  op while_do_ : K K -> K [prec 59 format (b o b on++i --)] .
--- Pgm
  op vars_;_ : KList K -> K [prec 121 format (b o b on++i --)] .
  ops print_ :  K -> K [prec 59 metadata "strict" format (b o d)] .
  op spawn_ : K -> K [prec 59 format(b n++i --)] .
  ops halt  : -> K [format (b o)] .
endm
