
# this is the name of the main maude module 
LANGUAGE_NAME = SIMPLE-TYPED-STATIC

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = SIMPLE-TYPED-SYNTAX SIMPLE-TYPED-STATIC-SEMANTICS SIMPLE-TYPED-STATIC

LATEX_STYLE = bb

#this is the basename of the main file
MAIN_FILE = simple-typed-static

# this is a space-separated list of basename maude files to run
TESTS = simple-typed-static-test.maude

TOOL_DIR =  $(K_CORE)/../tools/
include $(TOOL_DIR)make-helper.mk

