DEF=demo
EXT=demo
TESTDIR=.
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--syntax-module DEMO
KPROVE_FLAGS=

CONSIDER_PROVER_ERRORS=2>&1

export KOMPILE_BACKEND
export KPROVE_FLAGS

include ../include/ktest.mak
