SUBDIRS=issue-2273 concrete-function cell_map string_escape imp-kore poly-sort bit-range bit-range-ocaml cell-sort fresh1 fresh2 proj-attribute matching-attribute smt-prelude-attribute is-variable no-dup-rules

include ../../include/ktest-group.mak
