/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SglrJNI */

#ifndef _Included_SglrJNI
#define _Included_SglrJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SglrJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SglrJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     SglrJNI
 * Method:    parse
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SglrJNI_parse
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
