clean:
	rm -f *.o *.obj *.exe *.i *_ppp.c *.origi *~ *.s *.asm
	rm -f *cured.c *cil.c *infer.c *_comb.c *cabs.c *cured.optim.c
	rm -f *.pdb *.ilk *.stackdump a.out __scalar2pointer.txt
	rm -f *.html *.gif *.css
	rm -rf *.browser