MAKEFILE_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DEF=fun-type-inferencer
EXT=fun
TESTDIR=tests
KOMPILE_BACKEND?=java
KRUN_FLAGS=--pattern "<k> V:K </k>"

include $(MAKEFILE_PATH)/../../../../../../include/ktest.mak
