
# this is the name of the main maude module 
LANGUAGE_NAME = SIMPLE-TYPED-DYNAMIC

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = SIMPLE-TYPED-SYNTAX SIMPLE-TYPED-DYNAMIC-SEMANTICS SIMPLE-TYPED-DYNAMIC

LATEX_STYLE = bb

#this is the basename of the main file
MAIN_FILE = simple-typed-dynamic

# this is a space-separated list of basename maude files to run
TESTS = simple-typed-dynamic-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
