DEF=kool-typed-dynamic
EXT=kool
KRUN_FLAGS=--output none
TESTDIR?=../programs
RESULTDIR=tests

%/cycle.kool: kompile
	true
%/threads.kool: kompile
	true

include ../../../../../../../include/kframework/ktest.mak
