DEF=test
TESTDIR=.
KOMPILE_FLAGS=--syntax-module TEST
KOMPILE_BACKEND=haskell
export KORE_EXEC_OPTS=--log-level error

include ../../../include/kframework/ktest.mak

KPROVE_OR_X=$(KPROVEX)
CONSIDER_PROVER_ERRORS=2>&1
