DEF=test
TESTDIR=.
KOMPILE_FLAGS=--syntax-module TEST
KOMPILE_BACKEND=haskell
export KORE_EXEC_OPTS=--log-level error

include ../../../include/kframework/ktest.mak

KPROVE_OR_LEGACY=$(KPROVE)
CONSIDER_PROVER_ERRORS=2>&1
