MAKEFILE_PATH := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DEF=imp
DEFDIR=proof
EXT=imp
KOMPILE_BACKEND=haskell
KRUN_FLAGS=--output none
TESTDIR=tests/proofs

include $(MAKEFILE_PATH)/../../../find-k.mak
include ${K_HOME}/include/kframework/ktest.mak
KPROVE_OR_LEGACY=$(KPROVE)
