
# this is the name of the main maude module 
LANGUAGE_NAME = KOOL-UNTYPED

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = KOOL-UNTYPED-SYNTAX KOOL-UNTYPED

LATEX_STYLE = bb
#LATEX_TOPMATTER = README.tex

#this is the basename of the main file
MAIN_FILE = kool-untyped

# this is a space-separated list of basename maude files to run
TESTS = 

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
