TESTDIR=tests/nondeterministic
DEFDIR=nondet
DEF=lambda
EXT=lambda
KOMPILE_FLAGS=--syntax-module LAMBDA --enable-search
KRUN_FLAGS=--search --pattern "<k> V:K </k>"

include ../../../../../../include/kframework/ktest.mak

tests/nondeterministic/arithmetic-div-zero.lambda:
	true
