[project]
name = "a-semantics"
version = "0.1.0"
source = "."

[dependencies]
b-semantics = { path = "../b-semantics" }
c-semantics = { path = "../c-semantics" }

[targets.llvm]
main-file = 'a.k'
backend='llvm'
