DEF=../concrete-function/a
TESTDIR=.
EXT=a
KOMPILE_BACKEND=java
KOMPILE_FLAGS=--concrete-rules "A.f2"

include ../../../include/kframework/ktest.mak

KPROVE_OR_X=$(KPROVEX)
CONSIDER_PROVER_ERRORS=2>&1
