DEF=lambda
EXT=lambda
KOMPILE_FLAGS=--syntax-module LAMBDA
KOMPILE_BACKEND?=haskell
KRUN_FLAGS=--search --pattern "<tasks> <task> <k> T:Type </k> ...</task> </tasks>" --smt none

include ../../../../../../include/kframework/ktest.mak
