DEF=test
EXT=test
TESTDIR=.
KOMPILE_BACKEND=haskell
KRUN_FLAGS=--output kore
KOMPILE_FLAGS=--syntax-module TEST

include ../../../include/kframework/ktest.mak
# force krun instead of kx
KRUN_OR_KX=$(KRUN)
