package org.kframework.ktest2.CmdArgs;


import org.apache.commons.cli.CommandLine;
import org.apache.commons.io.FilenameUtils;
import org.kframework.krun.ColorSetting;
import org.kframework.ktest2.KTestStep;

import java.io.File;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents valid command line arguments. This class can only be instantiated using
 * `validateArgs' method, which ensures validation of arguments.
 *
 * Being valid means:
 *   - File paths are valid(e.g. point to a files/directories) relative to current directory
 *   - Only one unnamed argument is passed
 *   - File extension is either .k or .xml
 */
public class CmdArg {

    /**
     * A root directory where K definitions reside. By default this is the current directory.
     * Valid only in batch mode.
     */
    public final String directory;

    /**
     * Programs directory in single job mode, or a root directory for programs in batch mode. By
     * default this is the directory where <file> reside.
     */
    public final String programs;

    /**
     * Directory containing input and expected output for programs in single job mode,
     * or a root directory for the expected I/O for programs in batch mode. By default this is
     * the directory where <file> reside.
     */
    public final String results;

    /**
     * The list of program extensions separated by whitespaces. Required in single job mode,
     * invalid in batch mode.
     */
    public final String[] extensions;

    /**
     * The list of programs which will not be tested. Valid only in single job mode.
     */
    public final String[] excludes;

    /**
     * The list of steps separated by whitespace to be skipped.
     */
    public final Set<KTestStep> skips;

    /**
     * Generate a junit-like report.
     */
    public final boolean generateReport;

    /**
     * Config XML file for batch mode, K definition for single job mode.
     */
    public final String targetFile;

    /**
     * Enable verbose output.
     */
    public final boolean verbose;

    public final ColorSetting colorSetting;

    /**
     * Timeout for processes spawned by ktest. (in seconds)
     */
    public final int timeout;

    public CmdArg(String directory, String programs, String results, String[] extensions,
                   String[] excludes, Set<KTestStep> skips, boolean generateReport,
                   String targetFile, boolean verbose, ColorSetting colorSetting, int timeout) {
        this.directory = directory;
        this.programs = programs;
        this.results = results;
        this.extensions = extensions;
        this.excludes = excludes;
        this.skips = skips;
        this.generateReport = generateReport;
        this.targetFile = targetFile;
        this.verbose = verbose;
        this.colorSetting = colorSetting;
        this.timeout = timeout;
    }

    /**
     * Validate raw data parsed from command line arguments and return CmdArg objects,
     * which is needed for TestSuite to run tests.
     * @param cmdOpts CommandLine object generated by command line argument parser
     * @return validated CmdArg object that is needed by TestSuite
     * @throws InvalidArgumentException in case of an invalid argument
     */
    public static CmdArg validateArgs(CommandLine cmdOpts) throws InvalidArgumentException {
        String currentDir = System.getProperty("user.dir");
        String[] args = cmdOpts.getArgs();

        if (args.length != 1)
            throw new InvalidArgumentException("ktest requires exactly one <file> parameter.");

        String targetFile = FilenameUtils.concat(currentDir, args[0]);
        if (!new File(targetFile).isFile())
            throw new InvalidArgumentException("target file argument is not a valid file: " +
                    targetFile);

        String ext = FilenameUtils.getExtension(targetFile);
        if (!ext.equals("xml") && !ext.equals("k"))
            throw new InvalidArgumentException("target file format is not valid: " + ext +
                    "(should be .xml or .k)");

        String directory = getDirectoryArg(cmdOpts, Constants.DIRECTORY_OPTION,
                currentDir);
        String programs = getDirectoryArg(cmdOpts, Constants.PROGRAMS_OPTION,
                FilenameUtils.concat(currentDir, FilenameUtils.getFullPath(targetFile)));
        String results = getDirectoryArg(cmdOpts, Constants.RESULTS_OPTION,
                FilenameUtils.concat(currentDir, FilenameUtils.getFullPath(targetFile)));

        String[] extensions = cmdOpts.getOptionValue(Constants.EXTENSIONS_OPTION, "").split("\\s+");
        String[] excludes = cmdOpts.getOptionValue(Constants.EXCLUDE_OPTION, "").split("\\s+");

        boolean generateReport = cmdOpts.hasOption(Constants.REPORT_OPTION);

        boolean verbose = cmdOpts.hasOption(Constants.VERBOSE_OPTION);

        return new CmdArg(directory, programs, results, extensions, excludes, parseSkips(cmdOpts),
                generateReport, targetFile, verbose, parseColorSetting(cmdOpts),
                parseTimeout(cmdOpts));
    }

    private static int parseTimeout(CommandLine cmdOpts) throws InvalidArgumentException {
        String timeout_str = cmdOpts.getOptionValue(Constants.TIMEOUT_OPTION, "5000");
        try {
            return Integer.parseInt(timeout_str);
        } catch (NumberFormatException e) {
            throw new InvalidArgumentException("timeout value is not an integer: " + timeout_str);
        }
    }

    private static Set<KTestStep> parseSkips(CommandLine cmdOpts) throws InvalidArgumentException {
        Set<KTestStep> skips = new HashSet<>();
        for (String s : cmdOpts.getOptionValue(Constants.SKIP_OPTION, "").split("\\s+"))
            switch (s.trim()) {
                case "kompile": skips.add(KTestStep.KOMPILE); break;
                case "pdf": skips.add(KTestStep.PDF); break;
                case "krun": skips.add(KTestStep.KRUN); break;
                case "": break;
                default: throw new InvalidArgumentException("--" + Constants.SKIP_OPTION + " " +
                        "option should be [kompile|pdf|krun]+");
            }
        return skips;
    }

    private static ColorSetting parseColorSetting(CommandLine cmdOpts)
            throws InvalidArgumentException {
        String s = cmdOpts.getOptionValue(Constants.COLOR_SETTING, "on");
        switch (s) {
            case "on": return ColorSetting.ON;
            case "off": return ColorSetting.OFF;
            case "extended": return ColorSetting.EXTENDED;
            default: throw new InvalidArgumentException("--" + Constants.COLOR_SETTING + " option" +
                    " should be [on|off|extended]");
        }
    }

    private static String getDirectoryArg(CommandLine cmdOpts, String argName,
                                          String default_)
            throws InvalidArgumentException {
        final String ret = cmdOpts.getOptionValue(argName, default_);
        if (!new File(ret).isDirectory())
            throw new InvalidArgumentException("--" + argName + " argument is not a folder: " +
                    ret);
        return ret;
    }
}

