DEF=test
EXT=test
KOMPILE_BACKEND=haskell
TESTDIR=.
KPROVE_FLAGS+=--exclude VERIFICATION.fail1 --exclude VERIFICATION.fail2

include ../../../../include/kframework/ktest.mak

KPROVE_OR_LEGACY=$(KPROVE)
CONSIDER_PROVER_ERRORS=2>&1
