
# this is the name of the main maude module 
LANGUAGE_NAME = SIMPLY-TYPED-LAMBDA

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = SUBSTITUTION SIMPLY-TYPED-SEMANTICS

#this is the basename of the main file
MAIN_FILE = simply-typed-lambda

# this is a space-separated list of basename maude files to run
TESTS = simply-typed-lambda-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
