#!/bin/bash
SCRIPT_PATH=`which "$0"`
TOOLS_DIR=${SCRIPT_PATH%/*} 
MAUDE_LIB="$TOOLS_DIR/maude-bin" echo "" | "$TOOLS_DIR/maude-bin/maude" &>/dev/null
if [ "$?" -eq "0" ];
then
  MAUDE_LIB="$TOOLS_DIR/maude-bin" "$TOOLS_DIR/maude-bin/maude" "$@"
else
  maude "$@"
fi
