
# this is the name of the main maude module 
LANGUAGE_NAME = KERNELC-RELAXED

# this are all interesting modules (used to latexify)
LANGUAGE_MODULES = KERNELC-SYNTAX KERNELC-THREADS-SYNTAX KERNELC-DESUGARED-SYNTAX KERNELC-SEMANTICS  KERNELC-RELAXED-THREADS KERNELC-RELAXED

LATEX_TOPMATTER = README.tex

#this is the basename of the main file
MAIN_FILE = kernelc-relaxed

# this is a space-separated list of basename maude files to run
TESTS = kernelc-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
