
# this is the name of the main maude module 
LANGUAGE_NAME = FUN-UNTYPED

# the interesting modules we want to visualize
LANGUAGE_MODULES = FUN-UNTYPED-SYNTAX FUN-UNTYPED

LATEX_STYLE = bb
LATEX_TOPMATTER = README.tex

#this is the basename of the main file
MAIN_FILE = fun-untyped

# this is a space-separated list of basename maude files to run
TESTS = fun-untyped-test.m

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
