name: 'With K Docker'
description: 'Start a Docker container with the K .deb package installed'
inputs:
  container-name:
    description: 'Docker container name to use'
    required: true
    type: string
  k-deb-path:
    description: 'Path to K .deb file'
    required: true
    type: string
    default: kframework.deb
  distro:
    description: 'Distribution to setup Docker for.'
    required: true
    type: string
    default: jammy
  run-container:
    description: 'Run the K container automatically with default settings.'
    required: true
    type: boolean
    default: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      BASE_DISTRO: ${{ inputs.distro }}
      GH_TOKEN: ${{ github.token }}
      CONTAINER_NAME: ${{ inputs.container-name }}
      TAG: runtimeverificationinc/${{ inputs.container-name }}
    run: |
      set -euxo pipefail

      gh release download                           \
        --repo runtimeverification/llvm-backend     \
        --pattern "*ubuntu_${BASE_DISTRO}.deb"  \
        --output llvm-backend.deb                   \
        v$(cat deps/llvm-backend_release)

      DOCKERFILE=${{ github.action_path }}/Dockerfile
      K_DEB_PATH=${{ inputs.k-deb-path }}
      LLVM_BACKEND_DEB_PATH=llvm-backend.deb

      docker build . \
        --file ${DOCKERFILE}                                        \
        --tag ${TAG}                                                \
        --build-arg BASE_DISTRO=${BASE_DISTRO}                      \
        --build-arg K_DEB_PATH=${K_DEB_PATH}                        \
        --build-arg LLVM_BACKEND_DEB_PATH=${LLVM_BACKEND_DEB_PATH}

  - name: 'Run Docker container'
    shell: bash {0}
    if: ${{ inputs.run-container == 'true' }}
    run: |
      set -euxo pipefail

      docker run                 \
        --name ${CONTAINER_NAME} \
        --rm                     \
        --interactive            \
        --tty                    \
        --detach                 \
        --user root              \
        ${TAG}

      docker cp ./pyk/. ${CONTAINER_NAME}:/home/user
      docker exec ${CONTAINER_NAME} chown -R user:user /home/user
