load config.maude
load intsequence-theory.maude
---load list.maude


mod PL-BUILTINS is
---including BASIC-PL-BUILTINS .
including PL-BOOL .
including PL-EXT-BOOL .
including PL-NAT .
including PL-INT .
including PL-RAT .
including PL-FLOAT .
including PL-STRING .
including PL-CONVERSION .
including PL-QID .
including PL-RANDOM .
including PL-COUNTER .
including PL-BOOL .
including PL-ID .
  including CONFIG .
  including MATHEMATICAL-INT-SEQUENCE .
  ---including LIST-HP .
endm

