load fol.maude
load ml-imp.maude

mod TEST is inc IMP + FOL= . endm

set print attribute on .
---rew check('pSum) .
---rew check('pListReverse) .
---rew check('pListAppend) .
---rew check('pTreeMirror) .
rew check('pBstInsert) .


eof

search
< config >
  < newImpl > 1 </ newImpl >
  < env > a |-> a0 b |-> b0 x |-> ?x </ env >
  < heap > ?x |-> ?Int(1) : node ?x +Int 1 |-> b0 : next list(b0)(B) lseg(a0,
    ?x)(?A) </ heap >
  < form > ~ (?x === 0) /\ ~ (a0 === 0) /\ ?return === a0 </ form >
  < subst > !H <- list(b0)(B) </ subst >
</ config >
===>
< config >
    < env > a |-> ?a </ env >
    < heap > list(?a)(A ::: B) </ heap >
    < form > (~ (a0 === 0) /\ ?a === a0 \/ ?a === b0 /\ a0 === 0) /\ ?return
    === ?a </ form >
</ config >
=>* CfgItems:Bag
.

