TESTDIR=tests/deterministic
DEFDIR=det
DEF=lambda
EXT=lambda
KOMPILE_FLAGS=--gen-bison-parser

%/arithmetic-div-zero.lambda:
	true

include ../../../../../../include/kframework/ktest.mak
KOMPILE_FLAGS=--enable-search --syntax-module LAMBDA
KRUN_FLAGS=--pattern "<k> V:K </k>"
