#!/usr/bin/env bash
if [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
  "$(dirname "$0")/k.bat" "$@"
else
  source "$(dirname "$0")/setenv"
  ulimit -s `ulimit -H -s`
  #eval $JAVA -agentlib:jdwp=transport=dt_socket,server=n,address=Denis-PC:5005,suspend=y org.kframework.main.Main '"$@"'
  eval $JAVA org.kframework.main.Main '"$@"'
fi
