#!/usr/bin/env bash
if [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
  "$(dirname "$0")/k.bat" "$@"
else
  export K_OPTS="-Xms64m -Xmx1024m -Xss32m -XX:+TieredCompilation $K_OPTS"
  source "$(dirname "$0")/setenv"
  ulimit -s `ulimit -H -s`
  $JAVA org.kframework.main.Main "$@"
fi
