#!/usr/bin/env bash
if java -version 2>&1 | grep "64-Bit" >& /dev/null; then
  ARCH=64;
else
  ARCH=32;
fi

K_LIB_DIR="$(cd $(dirname "$0")/../lib; pwd)"
if [ `uname` = 'Darwin' ]; then
  export PATH=$PATH:"$K_LIB_DIR/native/osx"
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"$K_LIB_DIR/native/osx"
elif [[ `uname` == *MINGW* || `uname` == *CYGWIN* ]]; then
  export PATH=$PATH:"$K_LIB_DIR/native/windows":"$K_LIB_DIR/native/windows$ARCH":"$K_LIB_DIR/native/$ARCH"
else
  export PATH=$PATH:"$K_LIB_DIR/native/linux":"$K_LIB_DIR/native/linux$ARCH"
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$K_LIB_DIR/native/linux$ARCH"
fi

export CYGWIN=nodosfilewarning
