DEF=domains-lemmas-smt
EXT=dls
TESTDIR=.
KOMPILE_BACKEND=haskell
KPROVE_FLAGS=--def-module DOMAINS-LEMMAS-SMT
export KORE_EXEC_OPTS=--log-level error
KOMPILE_FLAGS=--syntax-module DOMAINS-LEMMAS-SMT

include ../../../include/kframework/ktest.mak
