name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    env:
      TAG_NAME: ${{ inputs.tag }}
    run: |
      Z3_VERSION=4.8.15
      K_VERSION=$(cat package/version)

      docker build . --file .github/workflows/Dockerfile.z3          --tag z3:${Z3_VERSION}
      docker build . --file .github/workflows/Dockerfile.stack-deps  --tag stack:${K_VERSION}
      docker build . --file .github/workflows/Dockerfile.maven-cache --tag maven:${K_VERSION}

      docker build . --file .github/workflows/Dockerfile \
          --tag runtimeverification/${TAG_NAME}          \
          --build-arg Z3_VERSION=${Z3_VERSION}           \
          --build-arg K_VERSION=${K_VERSION}             \
          --build-arg LLVM_VERSION=14                    \
          --build-arg USER_ID=$(id -u)

      docker run                          \
          --name ${TAG_NAME}              \
          --rm -it                        \
          --detach                        \
          --workdir /opt/workspace        \
          --user user:user                \
          -v ${HOME}:${HOME}              \
          -v "$(pwd):/opt/workspace"      \
          -v "/etc/passwd:/etc/passwd:ro" \
          -v "/etc/group:/etc/group:ro"   \
          runtimeverification/${TAG_NAME}
