name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default:
  distro:
    description: 'Distribution to setup Docker for.'
    required: true
  llvm:
    description: 'LLVM version to use.'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
      BASE_IMAGE: ${{ inputs.distro }}
      LLVM_VERSION: ${{ inputs.llvm }}
    run: |
      set -euxo pipefail

      Z3_VERSION=4.8.15
      K_VERSION=$(cat ${SUBDIR}package/version)

      docker build . --build-arg BASE_IMAGE=${BASE_IMAGE} --tag z3:${Z3_VERSION}   --file ${SUBDIR}.github/workflows/Dockerfile.z3
      docker build . --build-arg BASE_IMAGE=${BASE_IMAGE} --tag stack:${K_VERSION} --file ${SUBDIR}.github/workflows/Dockerfile.stack-deps
      docker build . --build-arg BASE_IMAGE=${BASE_IMAGE} --tag maven:${K_VERSION} --file ${SUBDIR}.github/workflows/Dockerfile.maven-cache

      docker build . --file ${SUBDIR}.github/workflows/Dockerfile    \
          --tag runtimeverification/${TAG_NAME}                      \
          --build-arg BASE_IMAGE=${BASE_IMAGE}                       \
          --build-arg Z3_VERSION=${Z3_VERSION}                       \
          --build-arg K_VERSION=${K_VERSION}                         \
          --build-arg LLVM_VERSION=${LLVM_VERSION}                   \
          --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)

      docker run                             \
          --name ${TAG_NAME}                 \
          --rm -it                           \
          --detach                           \
          --workdir /opt/workspace/${SUBDIR} \
          --user user:user                   \
          -v ${HOME}:${HOME}                 \
          -v "$(pwd):/opt/workspace"         \
          -v "/etc/passwd:/etc/passwd:ro"    \
          -v "/etc/group:/etc/group:ro"      \
          runtimeverification/${TAG_NAME}
