name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  tag:
    description: 'Docker image tag to use'
    required: true
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    default:
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      TAG_NAME: ${{ inputs.tag }}
      SUBDIR: ${{ inputs.subdir }}
    run: |
      set -x

      Z3_VERSION=4.8.15
      K_VERSION=$(cat ${SUBDIR}package/version)

      docker build . --file ${SUBDIR}.github/workflows/Dockerfile.z3          --tag z3:${Z3_VERSION}
      docker build . --file ${SUBDIR}.github/workflows/Dockerfile.stack-deps  --tag stack:${K_VERSION}
      docker build . --file ${SUBDIR}.github/workflows/Dockerfile.maven-cache --tag maven:${K_VERSION}

      docker build . --file ${SUBDIR}.github/workflows/Dockerfile    \
          --tag runtimeverification/${TAG_NAME}                      \
          --build-arg Z3_VERSION=${Z3_VERSION}                       \
          --build-arg K_VERSION=${K_VERSION}                         \
          --build-arg LLVM_VERSION=14                                \
          --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)

      docker run                             \
          --name ${TAG_NAME}                 \
          --rm -it                           \
          --detach                           \
          --workdir /opt/workspace/${SUBDIR} \
          --user user:user                   \
          -v ${HOME}:${HOME}                 \
          -v "$(pwd):/opt/workspace"         \
          -v "/etc/passwd:/etc/passwd:ro"    \
          -v "/etc/group:/etc/group:ro"      \
          runtimeverification/${TAG_NAME}
