#!/bin/sh -ex
cp -r /usr/share/kframework/pl-tutorial ~
WD=`pwd`
cd
echo 'Starting kserver...'
spawn-kserver $WD/kserver.log
cd pl-tutorial
echo 'Testing tutorial in user environment...'
make -j`nproc`
make clean
cd ~
echo "module TEST imports BOOL endmodule" > test.k
kompile test.k --backend haskell
rm -rf test-kompiled

# Make sure that the KLLVM bindings have been installed properly.
python3 <<HERE
import sys
sys.path = sys.path + ["$(llvm-kompile --bindings-path)"]
import kllvm

sort_int = kllvm.ast.CompositeSort("SortInt")
assert str(sort_int) == "SortInt{}"
HERE

# Make sure that the version of the various components is correct comparing to
# the KServer version that uses JVM.
VERSION_REGEX='v[0-9]+\.[0-9]+\.[0-9]+-[0-9]+-g[0-9a-z]+(-dirty)?'
KOMPILE_VERSION=$(kompile --version | grep -oP "${VERSION_REGEX}")
KSERVER_VERSION=$(kserver --version | grep -oP "${VERSION_REGEX}")

if [ "$KOMPILE_VERSION" != "$KSERVER_VERSION" ]; then
    echo "KOMPILE_VERSION: $KOMPILE_VERSION"
    echo "KSERVER_VERSION: $KSERVER_VERSION"
    exit 1
fi

# Make sure that the Haskell Backend Booster has been installed properly.
kore-rpc-booster --help
