DEF=set-balance
EXT=set-balance
KOMPILE_BACKEND=haskell
KOMPILE_FLAGS=--syntax-module SET-BALANCE
TESTDIR=.
KPROVE_FLAGS=--def-module VERIFICATION --md-selector 'keep&!(discard|k)'

include ../../../include/kframework/ktest.mak
