
# this is the name of the main maude module 
LANGUAGE_NAME = EXAMPLE

#this is the basename of the main file
MAIN_FILE = example

# this is a space-separated list of basename maude files to run
TESTS = test.m

IO_TESTS = programs/tests
IO_TEST_FLAG = "--output-mode=none"

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
