DEF=simple-typed-static
EXT=simple
TESTDIR?=../programs/*
RESULTDIR=tests
KOMPILE_FLAGS=--enable-search
KRUN_FLAGS=--pattern "<tasks> .Bag </tasks>" --smt none

include ../../../../../include/ktest.mak
