#!/bin/sh -ex
REV=$(cd .. && git rev-parse HEAD)
sed -i -e 's!^  url ".*"$!  url "file:///'$(pwd)'/../kframework-5.0.0.tar.gz"!' \
       -e 's!^  sha256 ".*"$!  sha256 "'$(sha256sum ../kframework-5.0.0.tar.gz | awk '{print $1}')'"!' \
    Formula/kframework.rb
git commit Formula/kframework.rb -m "Update kframework to $REV: part 1"
