#!/bin/sh -exu
REV=$1
sed -i "" -e 's!^  url ".*"$!  url "'$ROOT_URL/v$VERSION-$REV/$PACKAGE-$VERSION-src'.tar.gz"!' \
    Formula/$PACKAGE.rb
git commit Formula/$PACKAGE.rb -m "Update $PACKAGE to $REV: part 3"
cat Formula/$PACKAGE.rb
git push origin brew-release-$PACKAGE
