#!/bin/sh -ex
REV=$(cd .. && git rev-parse HEAD)
brew bottle --json kframework --root-url="https://github.com/kframework/k/releases/download/nightly-$REV/"
filename=$(cat *.bottle.json | jq -r '.kframework.bottle.tags.mojave.filename')
localfilename=$(cat *.bottle.json | jq -r '.kframework.bottle.tags.mojave.local_filename')
cat *.bottle.json
brew bottle --merge --write --no-commit *.bottle.json
mv $localfilename $filename
cp $(brew formula kframework) Formula/kframework.rb
git commit Formula/kframework.rb -m "Update kframeork to $REV: part 2"
