#!/bin/sh -exu
REV=$(cd .. && git rev-parse --short HEAD)
sed -i "" -e 's!^  url ".*"$!  url "'$ROOT_URL-$REV/$PACKAGE-$VERSION-src'.tar.gz"!' \
    Formula/$PACKAGE.rb
git commit Formula/$PACKAGE.rb -m "Update $PACKAGE to $REV: part 3"
cat Formula/$PACKAGE.rb
git push origin brew-release-$PACKAGE
