#!/usr/bin/env bash

set -e

notif() {
    echo -e "\n$@" \
            "\n================================================================================" \
            "\n" >&2
}

NPROCS="${NPROCS:-$(grep -c '^processor' /proc/cpuinfo)}"
WORKSPACE="${WORKSPACE:-$(pwd)}"
KSERVER_SOCKET="$WORKSPACE/kserver"
KSERVER_LOG="$WORKSPACE/kserver.log"
export KSERVER_SOCKET

notif "CLEANING REPO"
mvn clean
git clean -dfx

notif "SETTING UP OPAM/PERL ENVIRONMENTS"
eval `opam config env`
eval `perl -I$HOME/perl5/lib/perl5 -Mlocal::lib`

notif "CLONING SUBMODULES"
git submodule update --init

notif "BUILDING/RUNNING LOCAL TESTS"
mvn verify -U

notif "STARTING KSERVER"
./k-distribution/target/release/k/bin/spawn-kserver "$KSERVER_LOG"
sleep 5

notif "CLONING K EXERCISES"
rm -rf k-exercises
git clone 'git@github.com:kframework/k-exercises.git'

notif "RUNNING K EXERCISES"
(   cd k-exercises/tutorial
    make -j"$NPROCS"
)

notif "KILLING KSERVER"
./k-distribution/target/release/k/bin/stop-kserver || true

# notif "RUNNING RV-MATCH TESTS"
# cd ${WORKSPACE}
# rm -rf rv-match
# git clone git@github.com:runtimeverification/rv-match.git
# cd rv-match
# git submodule update --init -- c-semantics
# rm -rf k
# cp -r ${WORKSPACE}/k-pr k
# mvn verify -U -DskipKTest -DbuildProfile=x86_64-gcc-glibc
