#!/bin/sh -ex
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade --yes
apt-get install --yes opam
apt-get install --yes ./kframework_5.0.0_amd64.deb
"$(dirname "$0")/test-in-container"
