#!/bin/sh -ex
OPAMROOT=/usr/lib/kframework/opamroot k-configure-opam
eval $(opam config env)
cp -R /usr/share/kframework/pl-tutorial ~
WD=`pwd`
cd
echo 'Starting kserver...'
spawn-kserver $WD/kserver.log
cd pl-tutorial
echo 'Testing tutorial in user environment...'
make -j`nproc`
cd ~
echo "module TEST imports BOOL endmodule" > test.k
kompile test.k --backend ocaml
kompile test.k --backend haskell
