#!/bin/sh -ex
#cp -R /usr/share/kframework/pl-tutorial ~
ls
WD=`pwd`
cd
ls
echo 'Starting kserver...'
spawn-kserver $WD/kserver.log
cd test/smoke
echo 'Testing tutorial in user environment...'
make -j`nproc`
make clean
cd ~
echo "module TEST imports BOOL endmodule" > test.k
kompile test.k --backend haskell
rm -rf test-kompiled

# Make sure that the KLLVM bindings have been installed properly.
python3 <<HERE
import sys
sys.path = sys.path + ["$(llvm-kompile --bindings-path)"]
import kllvm

sort_int = kllvm.ast.CompositeSort("SortInt")
assert str(sort_int) == "SortInt{}"
HERE
