#!/bin/sh -ex
apt-get update
apt-get install -y ./kframework_5.0.0_amd64.deb
cp -R /usr/lib/kframework/tutorial ~
cd
echo 'Starting kserver...'
/usr/lib/kframework/bin/spawn-kserver kserver.log
cd tutorial
echo 'Testing tutorial in user environment...'
make -j`nproc`
