[
   K10Builtin                 -- _1 KW["("] _2 KW[")"],
   Map12Builtin               -- _1 KW["["] _2 KW["]"],
   Map13Builtin               -- _1 KW["["] _2 KW["/"] _3 KW["]"],
   Map14Builtin               -- _1 KW["["] KW["undef"] KW["/"] _2 KW["]"],
   ListDlKDr15Builtin         -- _1 KW["("] _2 KW[")"],
   Set16Builtin               -- KW["keys"] _1,
   Set17Builtin               -- KW["Set"] _1,
   Set18Builtin               -- _1 KW["-Set"] _2,
   Bag122Builtin              -- KW["Bag"] _1,
   Bag123Builtin              -- _1 KW["-Bag"] _2,
   List126Builtin             -- KW["List"] _1,
   KLabel136Builtin           -- KW["wrap-with"],
   KLabel137Builtin           -- KW["Int"] KW["("] _1 KW[")"],
   KLabel138Builtin           -- KW["Id"] KW["("] _1 KW[")"],
   KLabel139Builtin           -- KW["Float"] KW["("] _1 KW[")"],
   KLabel140Builtin           -- KW["Bool"] KW["("] _1 KW[")"],
   Ids1Empty                  -- KW[".Ids"],
   Exps1Empty                 -- KW[".Exps"],
   Ddecl1VarDeclSyn           -- KW["var"] _1 KW[";"],
   Exp1SizeSyn                -- KW["sizeOf"] KW["("] _1 KW[")"],
   Exp1Exp1ReadSyn            -- KW["read"] KW["("] KW[")"],
   Stmt1BlockEmptySyn         -- KW["{"] KW["}"],
   Stmt1BlockSyn              -- KW["{"] _1 KW["}"],
   Stmt1ReturnSyn             -- KW["return"] _1 KW[";"],
   Stmt1Return2Syn            -- KW["return"] KW[";"],
   Stmt1WriteSyn              -- KW["write"] KW["("] _1 KW[")"] KW[";"],
   Stmt1ThrowSyn              -- KW["throw"] _1 KW[";"],
   Stmt1AcquireSyn            -- KW["acquire"] _1 KW[";"],
   Stmt1ReleaseSyn            -- KW["release"] _1 KW[";"],
   Stmt1RendezvousSyn         -- KW["rendezvous"] _1 KW[";"],
   Stmt1PrintSyn              -- KW["print"] KW["("] _1 KW[")"] KW[";"],
   Val1ArrayRefSyn            -- KW["arrayRef"] KW["("] _1 KW[","] _2 KW[")"],
   Val1LambdaSyn              -- KW["lambda"] KW["("] _1 KW[","] _2 KW[")"],
   Vals1Empty                 -- KW[".Vals"],
   K1UndefinedSyn             -- KW["undefined"],
   K1ExecuteSyn               -- KW["execute"],
   K1LookupSyn                -- KW["lookup"] KW["("] _1 KW[")"],
   ListItem1MKBSyn            -- KW["("] _1 KW[","] _2 KW[","] _3 KW[")"],
   Val1NothingSyn             -- KW["nothing"],
   K1BindToSyn                -- KW["bindto"] KW["("] _1 KW[","] _2 KW[")"],
   K1EnvSyn                   -- KW["env"] KW["("] _1 KW[")"],
   ListItem1ISKMBSyn          -- KW["("] _1 KW[","] _2 KW[","] _3 KW[","] _4 KW[","] _5 KW[")"],
   K1PopxSyn                  -- KW["popx"],
   Exp1LValueSyn              -- KW["lvalue"] KW["("] _1 KW[")"],
   Val1LocSyn                 -- KW["loc"] KW["("] _1 KW[")"],
   ListDlKDr1DotDotSyn        -- _1 KW[".."] _2,
   Start12Var                 -- _1 KW[":"] KW["Start"],
   DzId12Var                  -- _1 KW[":"] KW["#Id"],
   Ddecl12Var                 -- _1 KW[":"] KW["Decl"],
   Stmts12Var                 -- _1 KW[":"] KW["Stmts"],
   KResult12Var               -- _1 KW[":"] KW["KResult"],
   Vals12Var                  -- _1 KW[":"] KW["Vals"],
   DzString12Var              -- _1 KW[":"] KW["#String"],
   Exp12Var                   -- _1 KW[":"] KW["Exp"],
   DzInt12Var                 -- _1 KW[":"] KW["#Int"],
   Stmt12Var                  -- _1 KW[":"] KW["Stmt"],
   KLabel12Var                -- _1 KW[":"] KW["KLabel"],
   Val12Var                   -- _1 KW[":"] KW["Val"],
   Ids12Var                   -- _1 KW[":"] KW["Ids"],
   DzBool12Var                -- _1 KW[":"] KW["#Bool"],
   Exps12Var                  -- _1 KW[":"] KW["Exps"],
   Start12Hole                -- KW["HOLE"] KW[":"] KW["Start"],
   DzId12Hole                 -- KW["HOLE"] KW[":"] KW["#Id"],
   Ddecl12Hole                -- KW["HOLE"] KW[":"] KW["Decl"],
   Stmts12Hole                -- KW["HOLE"] KW[":"] KW["Stmts"],
   KResult12Hole              -- KW["HOLE"] KW[":"] KW["KResult"],
   Vals12Hole                 -- KW["HOLE"] KW[":"] KW["Vals"],
   DzString12Hole             -- KW["HOLE"] KW[":"] KW["#String"],
   Exp12Hole                  -- KW["HOLE"] KW[":"] KW["Exp"],
   DzInt12Hole                -- KW["HOLE"] KW[":"] KW["#Int"],
   Stmt12Hole                 -- KW["HOLE"] KW[":"] KW["Stmt"],
   KLabel12Hole               -- KW["HOLE"] KW[":"] KW["KLabel"],
   Val12Hole                  -- KW["HOLE"] KW[":"] KW["Val"],
   Ids12Hole                  -- KW["HOLE"] KW[":"] KW["Ids"],
   DzBool12Hole               -- KW["HOLE"] KW[":"] KW["#Bool"],
   Exps12Hole                 -- KW["HOLE"] KW[":"] KW["Exps"],
   DzInt1Const                -- _1,
   DzBool1Const               -- _1,
   DzId1Const                 -- _1,
   DzString1Const             -- _1,
   KLabel1KLabelConst         -- _1,
   KLabel1Rewrite             -- _1 KW["=>"] _2,
   K1Hole                     -- KW["HOLE"],
   K12Hole                    -- KW["HOLE"] KW[":"] KW["K"],
   ListDlKDr1ListOfKWrap      -- _1,
   List1ListWrap              -- _1,
   Bag1BagWrap                -- _1,
   Set1SetWrap                -- _1,
   Map1MapWrap                -- _1,
   List12Var                  -- _1 KW[":"] KW["List"],
   List1Var                   -- _1,
   ListItem12Var              -- _1 KW[":"] KW["ListItem"],
   ListItem1Var               -- _1,
   Set12Var                   -- _1 KW[":"] KW["Set"],
   Set1Var                    -- _1,
   SetItem12Var               -- _1 KW[":"] KW["SetItem"],
   SetItem1Var                -- _1,
   Bag12Var                   -- _1 KW[":"] KW["Bag"],
   Bag1Var                    -- _1,
   BagItem12Var               -- _1 KW[":"] KW["BagItem"],
   BagItem1Var                -- _1,
   Map12Var                   -- _1 KW[":"] KW["Map"],
   Map1Var                    -- _1,
   MapItem12Var               -- _1 KW[":"] KW["MapItem"],
   MapItem1Var                -- _1,
   K12Var                     -- _1 KW[":"] KW["K"],
   K1Var                      -- _1,
   ListDlKDr12Var             -- _1 KW[":"] KW["List{K}"],
   ListDlKDr1Var              -- _1,
   KSentenceList              -- _1,
   KSentenceList.1:iter       -- _1,
   Config                     -- KW["configuration"] _1,
   K1Rule                     -- KW["rule"] _1 _2,
   List1Rule                  -- KW["rule"] _1 _2,
   Bag1Rule                   -- KW["rule"] _1 _2,
   ListDlKDr1Rule             -- KW["rule"] _1 _2,
   Set1Rule                   -- KW["rule"] _1 _2,
   Map1Rule                   -- KW["rule"] _1 _2,
   Context                    -- KW["context"] _1,
   AttributedCondSentence     -- _1 KW["when"] _2 KW["["] _3 KW["]"],
   CondSentence               -- _1 KW["when"] _2,
   AttributedSentence         -- _1 KW["["] _2 KW["]"],
   Bag1ClosedCell             -- KW["<"] _1 _2 KW[">"] _3 KW["</"] _4 KW[">"],
   Bag1ClosedCell.2:iter-star -- _1,
   LeftCell                   -- KW["..."] _1,
   RightCell                  -- _1 KW["..."],
   CellProperty               -- _1 KW["="] _2,
   CellLabelRewrite           -- _1 KW["=>"] _2,
   NoLabel                    -- ,
   Label                      -- KW["["] _1 KW["]"] KW[":"],
   NoTags                     -- ,
   TagList                    -- _1 KW[","] _2,
   Tag                        -- _1,
   TagParam                   -- _1 KW["("] _2 KW[")"],
   TagParam                   -- _1 KW["("] _2 KW[")"]
]