opam-version: "1"
version: "4.03.0"
src: "https://github.com/ocaml/ocaml/tarball/trunk"
build: [
  ["patch" "-p1" "-i" "%{root}%/repo/k/compilers/4.03.0/4.03.0+k/files/opam-compiler.patch"]
  ["./configure" "-prefix" prefix "-with-debug-runtime"]
  [make "world"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
