name: "Test"
on:
  pull_request:
jobs:
  compile-nix-flake:
    name: 'Nix flake'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2.3.4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v15

      - name: 'Install Cachix'
        uses: cachix/cachix-action@v10
        with:
          name: runtimeverification
          extraPullNames: kore
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: 'Add haskell.nix pub keys (macOS)'
        run: sed -i "" '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
        if: ${{ startsWith(matrix.os, 'macos') }}

      - name: 'Add haskell.nix pub keys (linux)'
        run: sed -i '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
        if: ${{ !startsWith(matrix.os, 'macos') }}

      - name: 'Add haskell.nix substituters (macOS)'
        run: sed -i "" '/^substituters =/ s/$/ https:\/\/cache.iog.io/' ~/.config/nix/nix.conf
        if: ${{ startsWith(matrix.os, 'macos') }}

      - name: 'Add haskell.nix substituters (linux)'
        run: sed -i '/^substituters =/ s/$/ https:\/\/cache.iog.io/' ~/.config/nix/nix.conf
        if: ${{ !startsWith(matrix.os, 'macos') }}

      - name: 'Build K Framework'
        run: GC_DONT_GC=1 nix build .