
# this is the name of the main maude module 
LANGUAGE_NAME = EXP-UNTYPED-ENVIRONMENT

# this are all interesting modules (used to latexify)
#LANGUAGE_MODULES = 

#this is the basename of the main file
MAIN_FILE = exp-untyped-environment

# this is a space-separated list of basename maude files to run
TESTS = 

TOOL_DIR =  $(K_BASE)/tools/
include $(TOOL_DIR)make-helper.mk
